D compiler checks
mesonbuild/meson pull request #10115
Opened 2022-03-11 21:44 UTC by rtbo

Implement and test a few compiler checks for D:
 - run
 - sizeof
 - has_header
 - alignment

May be a function to test built-in D versions would be useful too, but that would be specific to D.
Something like:
```meson
meson.get_compiler('d').has_version('LittleEndian')
```

2022-03-11 22:09 UTC, dcbaker requested changes
This probably deserves a release snippet, otherwise this looks good to me.

2022-03-12 20:06 UTC, dcbaker approved these changes

2022-03-24 14:21 UTC, dcbaker approved these changes

2022-04-30 14:07 UTC, merged

2022-05-01 22:50 UTC, eli-schwartz commented
Thinking more about this... I'm not sure what the best way to do it is, or even if we *can* do it at that level, but ideally we'd want a FeatureNew for this somehow? Can't think of a feasible way to return one from the individual compiler though.