CMake: fix custom target: directories are no longer used as inputs
mesonbuild/meson pull request #10303
Opened 2022-04-23 12:16 UTC by mensinda

2022-05-04 03:10 UTC, eli-schwartz requested changes

2022-05-04 03:10 UTC, eli-schwartz commented on mesonbuild/cmake/interpreter.py
> +            if not raw.is_absolute() and (self.current_src_dir / raw).exists() and (self.current_src_dir / raw).is_file():
```suggestion
            if not raw.is_absolute() and (self.current_src_dir / raw).is_file():
```

We don't need to check both.

2022-05-24 00:00 UTC, eli-schwartz commented on mesonbuild/cmake/interpreter.py
> +            if not raw.is_absolute() and (self.current_src_dir / raw).exists() and (self.current_src_dir / raw).is_file():
ping?

2022-05-24 18:06 UTC, jpakkane commented
Ping indeed, this is the last MR needed for 0.62.2.

2022-05-24 20:04 UTC, mensinda commented on mesonbuild/cmake/interpreter.py
> +            if not raw.is_absolute() and (self.current_src_dir / raw).exists() and (self.current_src_dir / raw).is_file():
Forgot about that one...

2022-05-24 22:00 UTC, merged