ninja backend: generate additional meta-rules for test/benchmarks targets
mesonbuild/meson pull request #10404
Opened 2022-05-18 05:25 UTC by eli-schwartz

'meson-test-prereq' now depends on any targets that were formerly added directly to 'all'. Behavior is not changed -- the all target still depends on this other meta-rule, and thus indirectly depends on all targets it used to depend on.

It is now possible to build just the targets needed for the testsuite and then e.g. run `meson test --no-rebuild`.

2022-05-18 19:59 UTC, lazka commented
(those MSYS2 errors could be because we updated to ninja 1.11.0 yesterday... let me know if I should investigate that somehow..)

2022-05-19 18:16 UTC, lazka commented
> (those MSYS2 errors could be because we updated to ninja 1.11.0 yesterday... let me know if I should investigate that somehow..)

ah, never mind; master CI ran through, sorry for the noise.

2022-05-19 18:34 UTC, lazka commented
ah, I missed it, let me check IRC logs.

2022-05-21 12:19 UTC, lazka commented
* ninja downgrade doesn't change anything
* "ninja explain" is written to stderr, while "ninja: no work to do." is written to stdout, so imo this depends on buffering/timing what you get first if you pipe them together.

If there is anything else I should look into/try, let me know.

2022-05-22 02:47 UTC, eli-schwartz commented
> "ninja explain" is written to stderr, while "ninja: no work to do." is written to stdout, so imo this depends on buffering/timing what you get first if you pipe them together.

That is... a good point. The platform tests invoke all commands with `stderr=subprocess.STDOUT` which in cases where you explicitly only want stdout seems a bit unfortunate...

2022-05-22 16:26 UTC, eli-schwartz commented
Alright, I tentatively added two preparatory commits to make the unittest handler be nicer about this.

2022-05-27 17:02 UTC, dcbaker requested changes
One small nit, but otherwise this looks good to me.

2022-06-13 22:02 UTC, dcbaker approved these changes

2022-06-13 23:00 UTC, merged