Better error message when custom_targets has duplicates in the output kwarg
mesonbuild/meson pull request #10736
Opened 2022-08-24 18:01 UTC by Volker-Weissmann

This patch changes 

```
ERROR: Multiple producers for Ninja target "file.c". Please rename your targets.
```
to 
```
meson.build:4:0: ERROR: custom_target: "output" keyword argument contains "file.c" multiple times
```

2022-09-28 02:48 UTC, tristan957 commented
@xclaesse thoughts on this one so it doesn't get forgotten?

2022-09-28 03:19 UTC, eli-schwartz requested changes
I think this would be much better done in mesonbuild/interpreter/type_checking.py in `_output_validator()`. In general, for anything that can be determined in an isolated manner we want to handle it in the type checking decorator.

2022-09-28 03:19 UTC, eli-schwartz commented on mesonbuild/interpreter/interpreter.py
> +                if kwargs['output'].count(el) > 1:
This is ruinously inefficient to repeatedly walk the entire list. I would instead suggest walking the list *once*, and alternately appending to either `seen` or `duplicates`

2022-09-29 17:00 UTC, Volker-Weissmann commented
> I think this would be much better done in mesonbuild/interpreter/type_checking.py in `_output_validator()`. In general, for anything that can be determined in an isolated manner we want to handle it in the type checking decorator.

I just commit that.
As to your performance argument: The slow part is only run if there are any duplicates, i.e. if it crashes. The critical part is
```
output_set = set(outputs)
if len(output_set) != len(outputs):
```
which is as fast as it gets.

2023-03-17 15:24 UTC, xclaesse commented
TIL a 1 line trick for this: `dups = {i for i, c in collections.Counter(kwargs['output']).items() if c > 1}`. As bonus it gives you all dups and not only the first one.

2023-03-17 15:36 UTC, eli-schwartz commented
> To code golf or not to code golf, that is the question.

I'm not really concerned about how many lines it takes, my original review comment mentioned algorithmic complexity in the error path.

2023-03-17 20:20 UTC, Volker-Weissmann commented
I did some measurements and the new code should be as fast as it gets.
If len(outputs) == 100000 and outputs[0] == outputs[-1] (which is the worst case) it takes 40 - 100 ms
I think the time-complexity is O(n*log(n)).

It only outputs the first duplicate, this is on purpose (I can output all duplicates if you object).

2023-03-17 22:04 UTC, merged

2023-03-17 22:28 UTC, Volker-Weissmann commented
Thank you very much for merging.

2023-03-17 22:43 UTC, eli-schwartz commented
Sorry for letting it slip under the radar for so long, I should have replied much much earlier.