Add console kvarg to run_target to let them be run in parallel
mesonbuild/meson pull request #11142
Opened 2022-12-05 20:51 UTC by mortie

`run_target` isn't always used for things which are singular long-running things which require direct console access like test suites. I have a project where I use one `run_target` per file for clang-tidy, like so:

```meson
if clang_tidy_prog.found()
  tidy_deps = []
  foreach path: tidy_files
    tidy_deps += run_target(
      '.tidy__' + path.replace('/', '__'),
      command: [
        clang_tidy_prog, '--quiet', '-p', meson.current_build_dir(),
        '--config-file=' + meson.current_source_dir() + '/.clang-tidy',
        meson.current_source_dir() + '/' + path,
      ],
    )
  endforeach
  alias_target('tidy', tidy_deps)
endif
```

Without this PR, those clang-tidy targets run sequentially. With this PR, I can add `console: false` to the `run_target` call and the targets run in parallel.

Note: This PR uses 0.65.0 as the `since` value for the `console` parameter. This might have to be changed.

2022-12-05 20:57 UTC, mortie commented
I force-pushed a modified commit with the `since` changed to 1.0.0 after discussion in IRC.

2022-12-05 20:59 UTC, eli-schwartz approved these changes
Makes sense.

2022-12-05 23:46 UTC, dcbaker requested changes
You need to add `console: bool` to the `RunTarget` class in interpreter/kwargs.py

2022-12-06 08:44 UTC, mortie commented
Done.

2022-12-06 17:52 UTC, jpakkane commented
Maybe this should be called `is_parallel` to match the signature of `test`.

2022-12-06 18:30 UTC, xclaesse commented
> Maybe this should be called `is_parallel` to match the signature of `test`.

I agree the term `console` seems to be leaking ninja specific implementation. It also very badly describe what that does, even for ninja it's a terrible naming. OTOH, we already have `console` kwarg on custom_target(), so it seems we lost on consistency already... My personal suggestion would be to go with `is_parallel` and deprecate `console` on custom_target() too.

2022-12-06 19:05 UTC, xclaesse commented
> There's no fundamental objective to preventing parallelism. Currently run_target disabled parallelism as a _**side effect**_ of setting a ninja option that is intended to "guarantee that a target which is manually/interactively run, correctly shows up on the console".

TBH I see that the opposite way, the main goal is to disable parallelism, console output is a natural side effect of that.

2022-12-06 19:51 UTC, xclaesse commented
> But you say that you see it contrary to the ninja documentation. Okay, let's roll with that. So -- who is it that specifically wants run_target to not run in parallel, but doesn't want to use `-j1` for this, and doesn't want to mark some run_targets as depending on others? What is an example use case of the feature "disable the parallelism, I dislike parallelism"?

When running any script that itself will spawn as many jobs as there are CPUs. Like running make/cargo in a custom target.

2022-12-06 21:30 UTC, mortie commented
So, the `console` option (both in `custom_target` and now potentially in `run_target`) does control whether the process spawned for running the command inherits the stdin/stdout/stderr file descriptors from the `ninja` process, or if the stdin is closed and stdout/stderr buffered. This has serious consequences which people care about (*especially* in the case of `run_target`):

* I can write a script which expects user input such as prompting the user for stuff. This doesn't even seem like an unintended use of `run_target`.
* Lots of tools change how their output looks based on whether stdout is a tty or not. Again, especially for `run_target`, there will be a lot of cases where the intention is for a human to invoke a `run_target` manually on the command line and look at the output.

There's a reason `console=true` is the default (and currently only) behavior, after all.

But then there are cases where we really don't care if the program inherits stdin/stdout/stderr or not. Running `clang-format` on a source file is a prime example of that.

So if we view the naming as UX, we have to decide whether we want to ask the question "Do you want this target to inherit its stdio from ninja?" or the question "Do you want to prevent this target from running in parallel with other targets where you have either implicitly or explicitly answered 'yes' to this question?". The phrasing of that second option is insane, but it's genuinely the best way I can think to phrase it:

* A run_target with `is_parallel=false` or an unspecified `is_parallel` would run in parallel with all other targets, except for other run_targets which also set `is_parallel=false` or leave `is_parallel` unspecified, or custom_targets which set `is_parallel=false`.
* A run_target with `is_parallel=true` would run in parallel with all other targets.
* A custom_target with `is_parallel=false` would run in parallel with all other targets, except for other other custom_targets which also set `is_parallel=false`, or run_targets which set `is_parallel=false` or leave `is_parallel` unspecified.
* A custom_target with `is_parallel=true` or an unspecified `is_parallel` would run in parallel with all other targets.

As a secondary effect, a run_target with `is_parallel=false` or an unspecified `is_parallel` would inherit its stdio from Ninja, and a custom_target with `is_parallel=false` (but not with an unspecified `is-parallel`) would inherit its stdio from Ninja. This is a non-obvious secondary effect which doesn't really make any sense unless you know the implementation detail that `is_parallel=false` is implemented using `pool=console` in the ninja file.

If we ask "Do you want this target to inherit its stdio from ninja?" we can instead just say: Only one target which inherits stdio from ninja can run at a time. run_target defaults to inheriting stdio, custom_target defaults to buffered stdio. And the secondary effect that only one process can inherit stdio at a time... makes all the sense in the world.

With tests, the situation is completely different. Whether tests inherit stdio or not is usually uninteresting, but we often care a whole lot about whether tests are run sequentially or _in parallel with other tests_. If I know my tests are messing with the filesystem or a database or anything else that's global state external to the process, I want the tests to run sequentially. If I know my tests are all isolated, I want the tests to run in parallel. If I have one test which I know messes with external global state, I want to ask Meson to run that test alone, but it can run all the other tests in parallel if it wants. In fact, I would probably prefer it if both `is_paralllel=false` tests and `is_parallel=true` tests use buffered output, just so that I don't have to deal with the test's behaviour differing based on the unrelated decision on whether to run them in parallel or not, and from what I can tell from the docs, the current implementation of `test()` agrees with me.

I would go as far as to argue that it would make sense to add a `console` option to `test()`. A test with `console=false, is_parallel=true` would run in parallel with everything, a test with `console=false is_parallel=false` would run in parallel with everything except tests, one with `console=true is_parallel=true` would inherit stdio and run in parallel with everything which doesn't also inherit stdio, and one with `console=true is_parallel=false` would run in parallel with everything except for other tests or other targets which inherit stdio. The fact that every point in this quadrant makes complete and total sense indicates strongly to me that there is a very weak connection between test's `is_parallel` option and the other targets's `console` option, so trying to force some spurious naming consistency here would be a large mistake in my opinion.

This got very long, sorry. TL;DR: I don't think `console` should be renamed to `is_parallel`.

2022-12-06 22:15 UTC, eli-schwartz commented
> When running any script that itself will spawn as many jobs as there are CPUs. Like running make/cargo in a custom target.

This is totally bogus, because what you actually want is for ninja to have GNU make jobserver/client support. There are unofficial patches for client support, and some people distribute a ninja edition that has those patches.

With recent versions of GNU Make, jobserver cooperation is much easier, so you can launch make as your top-level program, have it run the kitware fork of ninja, and have *that* run another make, and both ninja and the `custom_target()` retrieve job slots from your coordinating Make, sharing resources.

You don't want to arbitrarily disable this just because of some Meson kwarg that says "please attach stdin/stdout/stderr directly to the console, don't buffer it" which you were abusing in order to work around the original lack of jobserver support.

If you do have meson.build files which abuse this, do they have a project option for `-Dusing_kitware_ninja=true` that disables the console hack?

2022-12-07 16:26 UTC, xclaesse commented
> This is totally bogus, because what you actually want is for ninja to have GNU make jobserver/client support

I wouldn't say it's "totally bogus" just because there might be unofficial patches somewhere to make it work in some cases.

But I did not know that "console" means stdin also gets redirected, that's a good explanation why that's called "console", it's not even mentioned in our doc:

```
Keyword argument conflicts with capture, and is meant for commands that are resource-intensive and take a long time to finish. With the Ninja backend, setting this will add this target to [Ninja's console pool](https://ninja-build.org/manual.html#_the_literal_console_literal_pool), which has special properties such as not buffering stdout and serializing all targets in this pool.
```

I think that doc does a poor job at saying what it does.
- No mention of stdin.
- What is a "pool"? That's a very cryptic way of saying "does not run in parallel to other jobs" IMHO. Not even sure that's what it really means.
- What does that kwarg on other backends?

I'm not against using the term "console", but maybe we could just tweak a bit the doc to better explains what are the guarantees Meson gives, regardless of the implementation details in ninja. I guess that's
- Not buffered stdout.
- Inherit stdin.
- Not run in parallel to other jobs.

2022-12-14 07:56 UTC, Akaricchi commented
> Not run in parallel to other jobs.

In the case of `custom_target`, it definitely is ran parallel to other **non-console** jobs, so that's not entirely accurate.

2022-12-14 14:11 UTC, xclaesse commented
> In the case of `custom_target`, it definitely is ran parallel to other **non-console** jobs, so that's not entirely accurate.

That needs to be documented properly then.

2023-01-05 03:53 UTC, eli-schwartz requested changes
This still needs documentation. Please add:
- `docs/markdown/snippets/<name>.md` containing a changelog entry for this
- a kwargs entry to `docs/yaml/functions/run_target.yaml` describing the console kwarg, which can probably be partially copied from the similar docs in `docs/yaml/functions/custom_target.yaml`

Once that is complete I think this is ready to merge. Seems like we're all in agreement that this doesn't need changing from "console" to some other name...

2023-01-05 03:53 UTC, eli-schwartz commented on mesonbuild/interpreter/interpreter.py
> +        KwargInfo('console', bool, default=True, since='1.0.0'),
Can you bump the version to 1.1.0 here?

2023-02-27 19:12 UTC, eli-schwartz commented
Ping?

2023-12-22 19:17 UTC, closed without merging