meson init --build should call meson setup and meson compile
mesonbuild/meson pull request #11273
Opened 2023-01-10 18:40 UTC by bruchar1

Fixes #11235

2023-01-10 19:12 UTC, bruchar1 commented
> This is the only useful thing `compile` is doing (and the fact you ever need to do it is bad but that's VS architectural decisions for you).

Isn't `meson compile` allowing to be agnostic on the used backend?

2023-01-10 19:16 UTC, eli-schwartz commented
`meson init` never invokes `meson setup`  with the `--backend vs` option, I think. Which is the only case that the backend would be not-ninja.

2023-01-10 20:04 UTC, eli-schwartz requested changes
Can you please squash both commits into one? :)

2023-01-10 20:04 UTC, eli-schwartz commented on mesonbuild/minit.py
> +from .mesonlib import setup_vsenv
We can just use `mesonlib.setup_vsenv` instead of importing this import twice, probably.

2023-01-10 20:13 UTC, eli-schwartz approved these changes

2023-01-20 05:24 UTC, eli-schwartz commented on mesonbuild/minit.py
> +from mesonbuild import build, mesonlib
```suggestion
from mesonbuild import build, mesonlib, mlog
```

2023-01-22 07:25 UTC, merged