run_unittests: don't assume run from same directory
mesonbuild/meson pull request #11551
Opened 2023-03-19 01:48 UTC by scivision

For user-facing scripts it's nice to not assume they're run from the same directory. For example, when testing multiple Python versions by hand on a physical computer, without having to have all of the Python bin's on PATH. 

This is relevant say with the Python.org download binaries for Windows, which by default install to %LOCALAPPDATA%\Programs\Python\Python3x without version-named executables. I.e. python.exe not python3.12.exe

2023-03-19 01:56 UTC, eli-schwartz commented
Not sure I understand the purpose of running these scripts from anything other than the root meson directory. If you're testing multiple python versions by hand on a physical computer wouldn't you just run:
```
python3.8 run_unittests.py
python3.9 run_unittests.py
python3.10 run_unittests.py
python3.11 run_unittests.py
python3.12 run_unittests.py
```

That's what I do all the time...

2023-03-19 02:03 UTC, eli-schwartz requested changes

2023-03-19 02:03 UTC, eli-schwartz commented on run_unittests.py
> +        pytest_args.append(str(_pathlib.Path(__file__).resolve(strict=True)))
Why jump through hoops to convert `__file__` to several different types of objects and then right back to itself?
```suggestion
        pytest_args += [__file__]
```

2023-03-20 02:46 UTC, eli-schwartz approved these changes
I see... always Windows, in the end. :D

LGTM, although you might feel like updating the commit message in addition to the description? Dunno...

2024-05-01 17:28 UTC, bruchar1 commented
With 268276f7acc55a79fbd31a7d510af93d43ac2d8f, does this still applies?

2024-05-05 23:48 UTC, closed without merging