modules/rust: add bindgen_version method
mesonbuild/meson pull request #11679
Opened 2023-04-13 18:29 UTC by karolherbst

Bindgen drops or renames command line arguments, so it's helpful to know which version it has to supper older versions as well.

See https://gitlab.freedesktop.org/mesa/mesa/-/issues/8827

2023-04-13 18:34 UTC, dcbaker commented on mesonbuild/modules/rust.py
> +        return self._bindgen_version
I think we can actually use `self.bindgen.get_version()` here to get the version, and I think that caches internally so we wouldn't have to cache here.

2023-04-13 19:22 UTC, dcbaker requested changes

2023-04-13 19:22 UTC, dcbaker commented on mesonbuild/modules/rust.py
> +    def bindgen_version(self, state: ModuleState, args: T.List, kwargs: FuncBindgen) -> str:
```suggestion
   @noPosargs
   @noKwargs
    def bindgen_version(self, state: ModuleState, args: T.List, kwargs: T.Dict[str, T.Any]) -> str:
```

With the appropriate imports, and I think this is good to go

2023-04-13 19:30 UTC, dcbaker approved these changes
LGTM, thanks!

2023-04-14 10:29 UTC, xclaesse commented
You can already do find_program('bindgen', version: '>=0.xyz') to ensure you have the minimum version required. Isn't that enough? We could also add a method that returns the version on the program object, to have something generic instead of doing it only for bindgen.

2023-04-14 18:30 UTC, eli-schwartz commented
@xclaesse I already added precisely this to all ExternalProgramHolder objects in meson 0.62.0. The problem here is that the rust module doesn't provide a method that returns the found bindgen executable.

> You can already do find_program('bindgen', version: '>=0.xyz') to ensure you have the minimum version required. Isn't that enough?

I agree -- and also `find_program('bindgen').version()` -- and thus it makes me nervous to add a method to the rust module just to return the version string when this is already possible.

2023-04-14 19:27 UTC, xclaesse commented
Right, I think this PR can be closed then. @karolherbst does that covers your use-case?

2023-04-21 19:33 UTC, xclaesse commented
> I guess if meson makes the promise that this is the way of checking for the version, then I could use that instead, yeah.

Yep, that's the recommended way. Closing.

2023-04-21 19:33 UTC, closed without merging