Raise if a postconf script fails
mesonbuild/meson pull request #12115
Opened 2023-08-12 09:06 UTC by akihikodaki

Raise MesonException if a postconf script fails to let the user know about the failure.

2023-08-12 11:28 UTC, akihikodaki commented
I investigated the CI failure and it found `test cases/common/139 mesonintrospect from scripts` has been broken on Windows.

The arguments in the `MESONINTROSPECT` environment variable are escaped with the `join_args` function in `mesonbuild/utils/universal.py` for postconf scripts, and on Windows it emits a string that is incompatible with `shlex.split()` used in `check_introspection.py`. Even more oddly, the arguments in `MESONINTROSPECT` are always escaped with `shlex.quote()` in the other situations so that problem is specific to postconf scripts.

Here are possible ways to fix the bug:
1. Use `shlex.quote()` instead of `join_args` to escape the arguments in `MESONINTROSPECT` for postconf scripts. This breaks scripts that pass `MESONINTROSPECT` to Windows cmd.
2. Always use `join_args` to escape the arguments in `MESONINTROSPECT` and make `join_args` emit a string that is compatible with `shlex.split()`. More concretely, make it replace `\` with `\\`. This adds extra verbosity to `MESONINTROSPECT`.
3. Always use `join_args` to escape the arguments in `MESONINTROSPECT` and make `check_introspection.py` pass it to cmd on Windows. This abandons compatibility with `shlex.split()` and makes it harder to use `MESONINTROSPECT` in Python scripts.

2023-08-12 11:59 UTC, Volker-Weissmann commented
> I investigated the CI failure and it found `test cases/common/139 mesonintrospect from scripts` has been broken on Windows.
> 
> The arguments in the `MESONINTROSPECT` environment variable are escaped with the `join_args` function in `mesonbuild/utils/universal.py` for postconf scripts, and on Windows it emits a string that is incompatible with `shlex.split()` used in `check_introspection.py`. Even more oddly, the arguments in `MESONINTROSPECT` are always escaped with `shlex.quote()` in the other situations so that problem is specific to postconf scripts.
> 
> Here are possible ways to fix the bug:
> 
>     1. Use `shlex.quote()` instead of `join_args` to escape the arguments in `MESONINTROSPECT` for postconf scripts. This breaks scripts that pass `MESONINTROSPECT` to Windows cmd.
> 
>     2. Always use `join_args` to escape the arguments in `MESONINTROSPECT` and make `join_args` emit a string that is compatible with `shlex.split()`. More concretely, make it replace `\` with `\\`. This adds extra verbosity to `MESONINTROSPECT`.
> 
>     3. Always use `join_args` to escape the arguments in `MESONINTROSPECT` and make `check_introspection.py` pass it to cmd on Windows. This abandons compatibility with `shlex.split()` and makes it harder to use `MESONINTROSPECT` in Python scripts.

I think you should open a seperate issue for this.

2023-08-12 12:10 UTC, Volker-Weissmann requested changes

2023-08-12 12:10 UTC, Volker-Weissmann commented on mesonbuild/backend/backends.py
> +                raise MesonException(f'Postconf script \'{name}\' exit code {rc}')
```suggestion
                raise MesonException(f'Postconf script \'{name}\' failed with exit code {rc}.')
```

2023-08-12 13:32 UTC, Volker-Weissmann commented on mesonbuild/minstall.py
> +                print(f'FAILED: install script \'{name}\' failed with exit code {rc}, stopped')
```suggestion
                print(f'FAILED: install script \'{name}\' failed with exit code {rc}.')
```

2023-08-12 15:48 UTC, akihikodaki commented on mesonbuild/minstall.py
> +                print(f'FAILED: install script \'{name}\' failed with exit code {rc}, stopped')
Applied with commit d53e2662810da7d1dbd7a71dae1289fd95554e09.

2023-08-22 15:26 UTC, xclaesse commented
> Always use `join_args` to escape the arguments in `MESONINTROSPECT` and make `check_introspection.py` pass it to cmd on Windows. This abandons compatibility with `shlex.split()` and makes it harder to use `MESONINTROSPECT` in Python scripts.

I think we should do that for now because this PR is unrelated to that issue. You could then open a separate issue to discuss the quoting problem, because I think it's larger than `MESONINTROSPECT`, it affects every places we quote args to be used by external scripts, how are we expecting 3rd party to use those values.

2023-08-22 15:29 UTC, xclaesse commented
LGTM, if you can just make that CI pass.

2023-08-22 16:22 UTC, eli-schwartz commented
> Even more oddly, the arguments in `MESONINTROSPECT` are always escaped with `shlex.quote()` in the other situations so that problem is specific to postconf scripts.

This was changed for postconf in commit 522392e7553823e6b3ac38cadc4fbee72eae9540. Arguably, that's a bug and we should use shlex.quote...

2024-02-11 11:37 UTC, joukewitteveen commented
Now that #12807 is merged, rebasing the current pull request should fix CI.

2024-02-11 12:58 UTC, merged