Fix DUB dependencies (with cache description)
mesonbuild/meson pull request #12143
Opened 2023-08-20 12:44 UTC by rtbo

Two PR has been merged into DUB which will help to use DUB packages with Meson:
 - dlang/dub#2644
   - add the `dub describe` output the path of the built library in Dub's cache
 - dlang/dub#2647
   - add `dub build --deep` switch to build a complete tree of static libraries

`dub build --deep` will build exactly the same libraries (same build-id) as the packages returned by `dub describe`.
So for a complex dependency tree (e.g. `vibe-d`), a single command (entered by the user) will build all the needed sub-libraries, and then meson will be able to find them all in a single shot.

This PR fixes #11773 and supersedes #11798

2023-10-03 17:28 UTC, eli-schwartz commented on mesonbuild/dependencies/dub.py
> +            mlog.error('Failed to run {!r}', mlog.bold(dub_comp_id))
What is this printing? `{!r}` is what, here?

2023-10-07 12:45 UTC, rtbo commented
I have now `mypy` errors I didn't have:
```
 mesonbuild/dependencies/dub.py:30:26: error: Name "T.TypedDict" is not defined  [name-defined]
```
Is there a deprecation around `TypedDict`?

2024-02-08 05:20 UTC, denizzzka commented
@rtbo Thank you very much for the work on this PR! Is here any news?

2024-02-08 13:03 UTC, eli-schwartz commented
> Is there a deprecation around TypedDict?

Try importing it from typing_extensions instead, to handle versions of python before it was introduced.

2024-02-08 13:05 UTC, eli-schwartz commented
Also please remember to squash the lint changes into their respective commits once you are ready for merging.

2024-06-11 07:52 UTC, ricardaxel commented
Hello @rtbo, thanks for the work ! Is there any reason that this PR is not yet merged to master ?

2024-07-16 04:19 UTC, thesamesam commented
Could you look at the CI failures? Thanks.

2024-07-16 16:00 UTC, dcbaker requested changes
A couple of small (and one big) thing here. Thanks for looking at this

2024-07-16 16:08 UTC, eli-schwartz requested changes

2024-07-16 16:08 UTC, eli-schwartz commented on mesonbuild/dependencies/dub.py
> +                cmd = ['dub', 'build', '--deep']
Changes like this, that fix a previous commit, should be created with `git commit --fixup=old-commit` and squashed during rebasing.

2024-07-24 17:03 UTC, dcbaker commented
I really need this work to land soon, so I went ahead and squashed all of the fixups back into the commits they applied to, and applied the changes that Eli and I had requested. This is good stuff, and I'm excited to get it landed

2024-07-24 17:06 UTC, dcbaker approved these changes

2024-07-30 21:16 UTC, eli-schwartz commented on mesonbuild/dependencies/dub.py
> +            tgt_desc = targets[pkg["name"]]
Trivial nitpick.

```suggestion
            tgt_desc = targets[pkg['name']]
```

2024-08-06 15:35 UTC, closed without merging

2024-08-06 19:13 UTC, eli-schwartz commented
Thanks @thesamesam for debugging the cause of the Windows failure and fixing it.