Add FS module support for CustomTarget, CustomTargetIndex, and BuildTarget
mesonbuild/meson pull request #12409
Opened 2023-10-22 00:19 UTC by tristan957

2023-10-22 00:20 UTC, tristan957 commented
Please let me know if you think other APIs should have their support expanded.

2023-10-22 21:27 UTC, tristan957 commented
cc @anarazel, not sure if this helps

2023-10-22 21:52 UTC, anarazel commented
> cc @anarazel, not sure if this helps

@tristan957 I think it could - right now one of the uses in postgres has separate loops dealing with custom/build targets , various files and just strings. That'd be a easier to do if fs worked uniformly.

However, I don't think the feature really works at the moment?  Just passing a `CustomTarget, CustomTargetIndex, BuildTarget` to str(), results in `fs.name()` returning bogus results:
```
Message: t.full_path(): /srv/dev/build/postgres/m-dev-assert/src/include/catalog/postgres.bki , fs.name(): include', '--set-version=17', '--output=@OUTDIR@', '@INPUT@']>[postgres.bki]>
```

2023-10-22 21:53 UTC, tristan957 commented
Let me go ahead and add some tests to validate my work. Thanks for the feedback.

2023-10-22 21:57 UTC, anarazel commented
@tristan957 The reason for the behaviour I observed is that while `fs.relative_to()` has support to turn `CustomTargetIndex` et al to a path, `fs.name` etc don't.

2023-10-22 21:59 UTC, tristan957 commented
Hmmm. Must've missed something when I was reviewing my work. I had this shelved for a bit and then came back to it recently.

2023-10-22 22:12 UTC, tristan957 commented
I never actually implemented the changes, only added the FeatureNews, ....

2023-10-22 22:52 UTC, tristan957 commented
Added the support. I wonder if we should also add support for generators?

2023-10-22 23:17 UTC, anarazel commented on mesonbuild/modules/fs.py
> +            original = PurePath(state.backend.get_target_filename(arg))
This seems all quite redundant - perhaps worth creating new types to deduplicate typed arguments, and moving the type specific handling into a common function that gets the function name as an argument?

2023-10-22 23:18 UTC, anarazel commented
> Added the support.

Thanks, seems to work based on some fairly quick testing.

>  I wonder if we should also add support for generators?

Would be nice, the degree to which generator results behave differently from other things is painful...

2023-10-22 23:22 UTC, anarazel commented on test cases/common/220 fs module/meson.build
> +ctgt = fs.copyfile('ctgt.txt')
Perhaps worth testing the behaviour of a custom target with multiple outputs.

2023-10-23 19:48 UTC, tristan957 commented
> Would be nice, the degree to which generator results behave differently from other things is painful...

Let me look at generator...

2024-02-23 17:37 UTC, eli-schwartz requested changes

2024-02-23 17:37 UTC, eli-schwartz commented on mesonbuild/modules/fs.py
> +            FeatureNew('fs.is_absolute(file)', '0.59.0').use(state.subproject, location=state.current_node)
This should really be `fs.is_absolute with File arg` if you ask me...

2024-02-23 17:37 UTC, eli-schwartz commented on mesonbuild/modules/fs.py
> +        and so ALL '\\' are turned to '/', even if you meant to escape a character
So the issue here is that we actually do mean `\` and that is what people reading the file see, but pydoc sees  the single-quote being escaped?

```
Help on function as_posix in module mesonbuild.modules.fs:

as_posix(self, state: "'ModuleState'", args: 'T.Tuple[str]', kwargs: 'T.Dict[str, T.Any]') -> 'str'
    this function assumes you are passing a Windows path, even if on a Unix-like system
    and so ALL '' are turned to '/', even if you meant to escape a character
```

IMO the correct solution here is to change the docstring to `f"""`

2024-02-23 18:30 UTC, tristan957 commented
Fucking git

2024-02-23 18:33 UTC, tristan957 commented
> > Would be nice, the degree to which generator results behave differently from other things is painful...
> 
> Let me look at generator...

I don't think this is possible unless you can index GeneratedList, and I couldn't find any documentation that says you can.

2024-02-24 21:09 UTC, merged