Adding CLion to the list of the existing IDE integrations
mesonbuild/meson pull request #12650
Opened 2023-12-21 11:40 UTC by MarinaKalashina

Please consider the following changes to Documentation -> IDE integration -> Existing integrations:

- Added CLion to the list of integrations (https://www.jetbrains.com/help/clion/meson.html).
- Added "3rd party" to the Meson Syntax Highlighter plugin to indicate that it doesn't come from JetBrains.
- Sorted the list alphabetically.

Thank you!

2023-12-21 12:51 UTC, eli-schwartz requested changes
Can you fix the commit message to describe what it does?

2023-12-22 09:25 UTC, MarinaKalashina commented
> Can you fix the commit message to describe what it does?

Sure, done

2023-12-26 08:27 UTC, MarinaKalashina commented
Hello @eli-schwartz, is there anything else that needs fixing? Thank you

2023-12-26 13:08 UTC, eli-schwartz commented
See e.g. 

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
https://cbea.ms/git-commit/

"Changes introduced by this commit" is a bit cryptic as one-line summaries go.

2023-12-26 13:14 UTC, eli-schwartz commented
Consider the initial commit message:

```
Please consider the following changes to
Documentation -> IDE integration -> Existing integrations:

- Added CLion to the list of integrations (https://www.jetbrains.com/help/clion/meson.html).
- Added "3rd party" to the Meson Syntax Highlighter plugin to indicate that it doesn't come from JetBrains.
- Sorted the list alphabetically.

Thank you!
```

Vs the updated one:
```
Changes introduced by this commit: - Added CLion to the list of integrations (https://www.jetbrains.com/help/clion/meson.html). - Added "3rd party" to the Meson Syntax Highlighter plugin to indicate that it doesn't come from JetBrains. - Sorted the list alphabetically.
```

The primary issue with the first commit is that it was hard to read, it didn't clearly separate the one-line summary from the extended description.

The primary issue with the second commit is that the separation between the one-line summary and the extended description became less separated than it was before.

2023-12-27 10:19 UTC, MarinaKalashina commented
@eli-schwartz Thank you for explaining what was wrong with the commit message. Changed it one more time, hope everything is ok now :)

2023-12-27 14:25 UTC, merged