Allow using CustomTarget as test executable
mesonbuild/meson pull request #12897
Opened 2024-02-23 16:44 UTC by bruchar1

Fixes #6567

2024-02-23 16:49 UTC, dcbaker requested changes
Apart from missing `FeatureNew` checks, this looks good to me

2024-02-23 16:49 UTC, dcbaker commented on mesonbuild/interpreter/interpreter.py
> +    @typed_pos_args('benchmark', str, (build.Executable, build.Jar, ExternalProgram, mesonlib.File, build.CustomTarget, build.CustomTargetIndex))
We should have a `FeatureNew` here

2024-02-23 16:49 UTC, dcbaker commented on mesonbuild/interpreter/interpreter.py
> +    @typed_pos_args('test', str, (build.Executable, build.Jar, ExternalProgram, mesonlib.File, build.CustomTarget, build.CustomTargetIndex))
and here

2024-02-23 16:57 UTC, eli-schwartz requested changes

2024-02-23 16:57 UTC, eli-schwartz commented on docs/markdown/snippets/test_using_custom_target_executable.md
> +[[test]] function now accepts [[@custom_tg]] and [[@custom_idx]] for the
Missing "The" at the beginning of the sentence.

Second link should fail the "update website" CI.

2024-02-23 16:57 UTC, eli-schwartz commented on mesonbuild/mtest.py
> +            return test_cmd
How do we handle File and ExternalProgram here? This feels like we are not doing something earlier that we should have done...

2024-02-23 17:53 UTC, eli-schwartz commented on mesonbuild/mtest.py
> +            return test_cmd
Ugh, makes sense.

2024-02-24 17:08 UTC, dcbaker approved these changes

2024-02-24 17:08 UTC, merged