cargo: Load Cargo.lock
mesonbuild/meson pull request #12945
Opened 2024-03-07 18:14 UTC by xclaesse

Cargo.lock is essentially identical to subprojects/*.wrap files. When a
    (sub)project has a Cargo.lock file this allows automatic fallback for
    its cargo dependencies.

This is based on top of PRs https://github.com/mesonbuild/meson/pull/12944 and https://github.com/mesonbuild/meson/pull/12942.

2024-03-14 17:03 UTC, dcbaker requested changes
I've looked through the first 3 patches so far, and I have some small nits, but otherwise I'm happy for those to land.

I need to look at the last patch more

2024-03-14 17:26 UTC, dcbaker reviewed
What happens when the internet is not available?

Otherwise I'm okay with this. At some point I think we need to add the ability to update a Cargo.lock to `meson wrap`, but that's out of scope for this PR.

2024-03-14 17:26 UTC, dcbaker commented on docs/markdown/Wrap-dependency-system-manual.md
> +Since *1.4.0* Cargo wraps can also be provided with `Cargo.lock` file at the root
1.5.0

2024-03-14 17:32 UTC, xclaesse commented
> What happens when the internet is not available?

The good thing with Cargo.lock is it can generate wraps offline. If the subproject needs to be downloaded, it will check you don't have --wrap-mode=nodownload like any wrap file. This is just translating a Cargo.lock to a list of .wrap files.

2024-03-14 23:06 UTC, xclaesse commented on mesonbuild/cargo/interpreter.py
> +    def from_raw(cls, raw: manifest.DependencyV, name: str) -> Dependency:
Makes sense, yes. Changed in the PR this PR is based on: https://github.com/mesonbuild/meson/pull/12944.

2024-03-14 23:06 UTC, xclaesse commented on mesonbuild/cargo/interpreter.py
> +            self.api = list(api)[0]
Makes sense, yes. Changed in the PR this PR is based on: https://github.com/mesonbuild/meson/pull/12944.

2024-03-14 23:08 UTC, xclaesse commented on mesonbuild/cargo/interpreter.py
> +    if int(vers[0]) > 0:
I don't see why this could make a difference, but I changed to `!=0` which makes clear what we are checking here.

2024-06-14 17:20 UTC, jpakkane commented
Since this was ok'd, maybe just rebase and then merge?

2024-06-14 19:08 UTC, xclaesse commented
Missed that it was approved, rebased.

2024-06-14 19:59 UTC, merged

2024-06-14 20:11 UTC, eli-schwartz commented
Nice work!

> What happens when the internet is not available?

> The good thing with Cargo.lock is it can generate wraps offline. If the subproject needs to be downloaded, it will check you don't have --wrap-mode=nodownload like any wrap file. This is just translating a Cargo.lock to a list of .wrap files.

The neat thing if I understand here correctly, is that meson wraps need basically the same information as a Cargo.lock including the fact that both use sha256, right? So all information is in Cargo.lock, yeah.

2024-06-15 06:45 UTC, ognevny commented
excuse me, but can you give an example how this should work, please? I didn't understand this a bit

2024-06-16 02:46 UTC, eli-schwartz commented
> excuse me, but can you give an example how this should work, please? I didn't understand this a bit

- if you directly depend on a crate from crates.io and manually write a wrap file for it, meson will parse a Cargo.lock from inside the crate to detect recursive dependencies and handle downloading them as subprojects
- if your project uses meson but also has a Cargo.lock (I dunno why, maybe you want it to be available with both build systems? maybe you want to use cargo to handle dependency resolution but want to use meson for the actual build?) then it will parse that to detect top-level and also recursive dependencies and handle downloading them as subprojects

2024-06-16 06:21 UTC, ognevny commented
> - if your project uses meson but also has a Cargo.lock (I dunno why, maybe you want it to be available with both build systems? maybe you want to use cargo to handle dependency resolution but want to use meson for the actual build?) then it will parse that to detect top-level and also recursive dependencies and handle downloading them as subprojects

that's my case. is there any extra thing that is needed ro be added for meson.build?

2024-06-17 05:58 UTC, ognevny commented
> that's my case. is there any extra thing that is needed ro be added for meson.build?

details: I have a repo with code in different languages, so I created `meson.build` at root of project, which defines 3 subdirectories. one of them for a rust source. it's actually a cargo workspace with multiple cargo projects, but it has Cargo.lock on top of them (so it's located in `root/subdir/Cargo.lock`). what should I do with `root/subdir/meson.build` file?

<details><summary>meson.build</summary>

```meson
src_rust = [
  'ege1/src/main.rs',
  'first_word/src/main.rs',
  'integral/src/main.rs',
  'last_word/src/main.rs',
  'longman/src/main.rs',
  'longman2/src/main.rs',
  'mask1/src/main.rs',
  'mcko/src/main.rs',
  'pop/src/main.rs',
  'probnik/src/main.rs',
  'resheto/src/main.rs',
  'speedometer/src/main.rs',
  'tumba-umba/src/main.rs',
]

foreach file : src_rust
  executable(file.split('/')[0], file)
endforeach
```

</details>

2024-06-17 14:43 UTC, xclaesse commented
@ognevny currently the rust part would have to be in `subprojects/` to make the main project consume it as a subproject. In can still be in the same  git repo.

2024-06-17 14:50 UTC, ognevny commented
> @ognevny currently the rust part would have to be in `subprojects/` to make the main project consume it as a subproject. In can still be in the same  git repo.

I moved it into `<root>/subprojects/rusted` and It still doesn't load Cargo.lock. should be wrap file created manually?

2024-06-18 03:25 UTC, xclaesse commented
> I moved it into `<root>/subprojects/rusted` and It still doesn't load Cargo.lock. should be wrap file created manually?

It should load it when the main project does `subproject('rusted')`. I can give it a try if you push your updated project somewhere.

2024-06-18 12:39 UTC, xclaesse commented
@ognevny if you want to take advantage of the Cargo support in Meson you need to remove subprojects/rusted/meson.build and add method=cargo in subprojects/rusted.wrap.

2024-06-18 12:42 UTC, ognevny commented
> @ognevny if you want to take advantage of the Cargo support in Meson you need to remove subprojects/rusted/meson.build and add method=cargo in subprojects/rusted.wrap.

and this didn't work because it tries to find `rusted` package, but cargo workspaces can't have a name on top Cargo.toml

2024-06-18 12:58 UTC, ognevny commented
and what means 0 targets to build for other packages?

2024-06-18 13:24 UTC, xclaesse commented
Workspace Cargo.toml are not supported yet, I think that's why it crash like that.

> edit: and what means 0 build targets for other packages?

Do they have a [lib] section?

2024-06-18 13:31 UTC, ognevny commented
> > edit: and what means 0 build targets for other packages?
> 
> Do they have a [lib] section?

no, they are intended to be a binaries

2024-06-18 17:27 UTC, xclaesse commented
> no, they are intended to be a binaries (executables)

That's not yet supported I think.

2024-06-18 17:29 UTC, ognevny commented
> > no, they are intended to be a binaries (executables)
> 
> That's not yet supported I think.

yes, it doesn't read [[bin]] entries

2024-07-16 17:16 UTC, pbo-linaro commented
I'm trying to use this new feature in meson 1.5.0.
I managed to generate wrap by defining a subproject with my library (+ a lib.wrap, with `method=cargo`), and its dependencies wrap are generated as expected,

However, the documentation mentions it should work with toplevel cargo.lock too (and not in a subproject).
Is it supported?

2024-07-16 19:18 UTC, pbo-linaro commented
Found the issue. The dependency I was loading didn't have the expected name.

It follows a specific convention for version in `{crate}-{version}-rs`:
https://github.com/mesonbuild/meson/blob/a51d5f36da85c1652c20254a522a9448147c4fbf/mesonbuild/cargo/interpreter.py#L371

```
x.y.z -> x
0.x.y -> 0.x
0.0.x -> 0
```

It makes sense, but maybe it would be better to emit an error when user try to specify full version.
```
dependency('crate-1.2.3-rs') -> "dependency crate version should be 1 instead of 1.2.3"
```

2024-07-17 12:12 UTC, xavierclaessens commented
That's documented here: https://mesonbuild.com/Wrap-dependency-system-manual.html#cargo-wraps. I'm not sure we can really warn in this case because you could in theory handwrite a meson.build file that provides `crate-1.2.3-rs` dependency. The automatic cargo subproject uses a convention but not everyone is forced to follow it when porting manually.

2024-07-17 15:17 UTC, pbo-linaro commented
When a user specifies a `*-rs` dependency, if no wrap file is found for the crate name, then they probably expect `Cargo.lock` strategy to be used. And if someone really tries to write a wrap file, they probably know what they are doing.
Then, it could be useful to report: "No Cargo.lock file were found", and check the version thing according to the convention used.

I have probably been unlucky in my attempt, but just having a message similar to:
`can't find dependency crate-1.2.3-rs (using CMake or pkg-config)` is confusing, when you are trying to get it using `Cargo.lock`. And even though the version thing is documented, it's easy to make the mistake.

I think this new feature is very important, and really make it easy to use crates from meson.

2024-07-17 15:50 UTC, xclaesse commented
I understand that error is confusing, especially since it says it tried CMake and pkg-config which is not entirely true, it also looked a subproject providing it from Cargo.lock or subprojects/*.wrap.

The problem is not that Cargo.lock is not found, meson did read your Cargo.lock, but it defines `crate-1-rs` dependency name and not `crate-1.2.3-rs`. Meson cannot know your intention, it could be a typo in dependency name, or maybe you intended to provide `subprojects/crate-1.2.3-rs.wrap`, or maybe the name is wrong in your Cargo.lock... 

I guess the error message could be improved with some heuristic, like if the name is in the form `<name>-<version>-rs` and we have a Cargo subproject with the same `<name>` it could suggest that it's maybe a typo. I'm always open to better error messages, want to make a PR?

2024-07-17 16:01 UTC, pbo-linaro commented
> I understand that error is confusing, especially since it says it tried CMake and pkg-config which is not entirely true, it also looked a subproject providing it from Cargo.lock or subprojects/*.wrap.
>

We could add "tried Cargo import", so people know that yes, Cargo.lock was found.
 
> The problem is not that Cargo.lock is not found, meson did read your Cargo.lock, but it defines `crate-1-rs` dependency name and not `crate-1.2.3-rs`. Meson cannot know your intention, it could be a typo in dependency name, or maybe you intended to provide `subprojects/crate-1.2.3-rs.wrap`, or maybe the name is wrong in your Cargo.lock...
>

I got it, but if there is a Cargo.lock, no wrap file, and a full version number (>= 1.x), it should not be a false positive to suggest to user to change its version.

> I guess the error message could be improved with some heuristic, like if the name is in the form `<name>-<version>-rs` and we have a Cargo subproject with the same `<name>` it could suggest that it's maybe a typo. I'm always open to better error messages, want to make a PR?

I'll take a look at it, but not sure when I'll have time for it.
Wanted to make sure first that this would be a direction you would agree with before investing energy into this.

2024-07-19 00:45 UTC, pbo-linaro commented
Created a PR for that https://github.com/mesonbuild/meson/pull/13448

2024-07-23 17:39 UTC, ognevny commented
@xavierclaessens there been a long since my last comment. I finally refactored my code to be a library. it's still avialable at https://github.com/ognevny/my-code/tree/refactor-meson, but now I get new errors

<details><summary>meson log</summary>

```
The Meson build system
Version: 1.5.0
Source dir: /home/ogn/upstream/my-code
Build dir: /home/ogn/upstream/my-code/build
Build type: native build
Project name: ognevny-my-code
Project version: 0.0.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Rust compiler for the host machine: rustc -C linker=cc (rustc 1.79.0)
Rust linker for the host machine: rustc -C linker=cc ld.bfd 2.42.0

Executing subproject rusted method cargo

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mesonbuild/mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 364, in run
    app.generate()
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 187, in generate
    return self._generate(env, capture, vslite_ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/msetup.py", line 226, in _generate
    intr.run()
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 3032, in run
    super().run()
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 169, in run
    self.evaluate_codeblock(self.ast, start=1)
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 219, in evaluate_statement
    return self.evaluate_if(cur)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 309, in evaluate_if
    self.evaluate_codeblock(i.block)
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreterbase/decorators.py", line 569, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 867, in func_subproject
    return self.do_subproject(args[0], kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 948, in do_subproject
    raise e
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 936, in do_subproject
    return methods_map[method](subp_name, subdir, default_options, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/interpreter/interpreter.py", line 1044, in _do_subproject_cargo
    ast, options = cargo.interpret(subp_name, subdir, self.environment)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/cargo/interpreter.py", line 708, in interpret
    manifests = _load_manifests(os.path.join(env.source_dir, subdir))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/cargo/interpreter.py", line 338, in _load_manifests
    manifest_ = _convert_manifest(raw_manifest, subdir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/cargo/interpreter.py", line 313, in _convert_manifest
    {k: Dependency.from_raw(k, v) for k, v in raw_manifest.get('dependencies', {}).items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mesonbuild/cargo/interpreter.py", line 190, in from_raw
    return cls(name, **_fixup_raw_mappings(raw))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Dependency.__init__() missing 1 required positional argument: 'version'

meson.build:27:2: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
```

</details>

2024-07-23 18:08 UTC, ognevny commented
> there been a long since my last comment. I finally refactored my code to be a library. it's still avialable at https://github.com/ognevny/my-code/tree/refactor-meson, but now I get new errors
> meson log

that's the issue with meval dependency. when I switched to dependency available in https://crates.io (instead of fork in github) everything went fine. thanks for a such change anyway!

2024-08-15 09:05 UTC, nirbheek commented
This has caused a regression in the minimum python version when building any project that contains a Cargo.lock in the source root, even if it uses meson.build to build it, such as librsvg or gst-plugins-rs and will not make use of the automated wrap deduction using Cargo.lock:

```
$ python3 --version
Python 3.10.12
$ MESON_FORCE_BACKTRACE=1 ../meson/meson.py builddir
The Meson build system
Version: 1.5.99
Source dir: /root/librsvg
Build dir: /root/librsvg/builddir
Build type: native build

meson.build:1:0: ERROR: Could not find an implementation of tomllib, nor toml2json

A full log can be found at /root/librsvg/builddir/meson-logs/meson-log.txt
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Traceback (most recent call last):
  File "/root/librsvg/../meson/meson.py", line 27, in <module>
    sys.exit(mesonmain.main())
  File "/root/meson/mesonbuild/mesonmain.py", line 288, in main
    return run(sys.argv[1:], launcher)
  File "/root/meson/mesonbuild/mesonmain.py", line 279, in run
    return CommandLineParser().run(args)
  File "/root/meson/mesonbuild/mesonmain.py", line 190, in run
    return errorhandler(e, command)
  File "/root/meson/mesonbuild/mesonmain.py", line 31, in errorhandler
    raise e
  File "/root/meson/mesonbuild/mesonmain.py", line 188, in run
    return options.run_func(options)
  File "/root/meson/mesonbuild/msetup.py", line 365, in run
    app.generate()
  File "/root/meson/mesonbuild/msetup.py", line 188, in generate
    return self._generate(env, capture, vslite_ctx)
  File "/root/meson/mesonbuild/msetup.py", line 210, in _generate
    intr = interpreter.Interpreter(b, user_defined_options=user_defined_options)
  File "/root/meson/mesonbuild/interpreter/interpreter.py", line 322, in __init__
    self.parse_project()
  File "/root/meson/mesonbuild/interpreterbase/interpreterbase.py", line 129, in parse_project
    self.evaluate_codeblock(self.ast, end=1)
  File "/root/meson/mesonbuild/interpreterbase/interpreterbase.py", line 195, in evaluate_codeblock
    raise e
  File "/root/meson/mesonbuild/interpreterbase/interpreterbase.py", line 187, in evaluate_codeblock
    self.evaluate_statement(cur)
  File "/root/meson/mesonbuild/interpreterbase/interpreterbase.py", line 201, in evaluate_statement
    return self.function_call(cur)
  File "/root/meson/mesonbuild/interpreterbase/interpreterbase.py", line 528, in function_call
    res = func(node, func_args, kwargs)
  File "/root/meson/mesonbuild/interpreterbase/decorators.py", line 250, in wrapper
    return f(*nargs, **wrapped_kwargs)
  File "/root/meson/mesonbuild/interpreterbase/decorators.py", line 569, in wrapper
    return f(*wrapped_args, **wrapped_kwargs)
  File "/root/meson/mesonbuild/interpreter/interpreter.py", line 1294, in func_project
    r = wrap.Resolver(self.environment.get_source_dir(), subdir, self.subproject, wrap_mode)
  File "<string>", line 10, in __init__
  File "/root/meson/mesonbuild/wrap/wrap.py", line 314, in __post_init__
    self.load_wraps()
  File "/root/meson/mesonbuild/wrap/wrap.py", line 331, in load_wraps
    for wrap in cargo.load_wraps(source_dir, self.subdir_root):
  File "/root/meson/mesonbuild/cargo/interpreter.py", line 745, in load_wraps
    cargolock = T.cast('manifest.CargoLock', load_toml(filename))
  File "/root/meson/mesonbuild/cargo/interpreter.py", line 64, in load_toml
    raise MesonException('Could not find an implementation of tomllib, nor toml2json')
mesonbuild.utils.core.MesonException: Could not find an implementation of tomllib, nor toml2json
```

2024-08-15 09:24 UTC, sdroege commented
I don't think this is a useful default behaviour, and especially it diverges from the behaviour of cargo: cargo only loads the Cargo.lock of the project itself, not of any of its dependencies.

The problems this will cause in practice is that if your project depends on some Rust crate that didn't get updated since quite a while, an ancient Cargo.lock with old dependency versions will get loaded despite *your* project having a Cargo.lock that includes all these dependencies in newer versions already. Even if *your* project's Cargo.lock gets preference, this would mean that potentially unnecessary dependencies get added as subprojects (example: old Cargo.lock had a transitive dependency that is not a dependency anymore with newer versions), or dependency conflicts between the two could appear.

Cargo.lock already include all transitive dependencies and there's no point in considering multiple of them, and considering any Cargo.lock than the one of the root project will cause all kinds of confusing problems.

@xclaesse I told you this multiple times on IRC in the past so I'm surprised that this just got merged as if this is the obviously correct way of doing things and there are no potential problems with it. I hope this gets reconsidered and can be changed in a later version still, otherwise this makes cargo subprojects in meson useless for the general case.

2024-08-15 12:33 UTC, xclaesse commented
@sdroege that's not true, the Cargo.lock from main project takes precedence over those from subprojects. Since Cargo always define all transitive dependencies in the root Cargo.lock, all those from subprojects will just be no-op. If they define extra dependencies that does not mean they'll be configured. That's controlled with feature options, what is inside Cargo.lock does not change anything.

The reason I'm loading Cargo.lock from subprojects is because the main project might not have one at all (e.g. use-case of Mesa).

The issue reported by @nirbheek is trivial to fix, I'll open a PR asap.

2024-08-15 12:34 UTC, xclaesse commented
Think about Cargo.lock as being identical behaviour has having subprojects/*.wrap. That's literally just a different file format for the exact same info.

2024-08-15 13:15 UTC, xclaesse commented
@nirbheek should be fixed by https://github.com/mesonbuild/meson/pull/13547.

2024-08-15 19:35 UTC, sdroege commented
@xclaesse Thanks for the clarification, that indeed makes more sense. Sorry for not checking in detail first how it behaves.