Cython generator for init command
mesonbuild/meson pull request #13245
Opened 2024-05-22 20:26 UTC by dreamer-coding-555

Just adding a new Cython generator to the template command.

2024-05-22 22:12 UTC, eli-schwartz requested changes

2024-05-22 22:12 UTC, eli-schwartz commented on docs/markdown/snippets/new_cython_template.md
> +Meson now includes a convenient option to generate a new `cython` project using the `init` command. This feature allows developers to quickly set up a `cython` project structure with the necessary fi
Doesn't mention the command. :P 

The wording feels a bit overly descriptive but I can't put a finger on why.

I would suggest using linebreaks to do wrapping -- this is explicitly markdown which means multiple lines equal a single paragraph unless there are empty lines separating them.

2024-05-22 22:12 UTC, eli-schwartz commented on mesonbuild/templates/cythontemplates.py
> +hello_pyx_meson_template = '''project('{project_name}', 'python',
Has this been tested? Because this isn't a valid language... it's not the language of the template itself...

2024-05-22 22:12 UTC, eli-schwartz commented on mesonbuild/templates/cythontemplates.py
> +  install : true)
Doesn't compile successfully.

```
[2/3] Compiling C object cythonproj.p/meson-generated_cythonproj.pyx.c.o
FAILED: cythonproj.p/meson-generated_cythonproj.pyx.c.o 
ccache cc -Icythonproj.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O0 -g -MD -MQ cythonproj.p/meson-generated_cythonproj.pyx.c.o -MF cythonproj.p/meson-generated_cythonproj.pyx.c.o.d -o cythonproj.p/meson-generated_cythonproj.pyx.c.o -c cythonproj.p/cythonproj.pyx.c
cythonproj.p/cythonproj.pyx.c:16:10: fatal error: Python.h: No such file or directory
   16 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

2024-05-22 22:12 UTC, eli-schwartz commented on mesonbuild/templates/cythontemplates.py
> +hello_pyx_template = '''print("This is project {project_name}.")'''
File should end with `\n`.

```suggestion
hello_pyx_template = '''print("This is project {project_name}.")
'''
```

Also double quotes -> single quotes?

2024-05-22 23:56 UTC, dreamer-coding-555 commented
Alright, I'll be sure to look through the requested changes was wrapping up a few experiments before jumping back.

2024-05-23 13:15 UTC, dnicolodi commented
Does it make sense to have a template for building a stand alone executable, a shared library, or a static library with Cython? While it is technically possible, I believe that in 99.9% of the cases, Cython is used to build Python extensions. Anyhow, the `meson.build` proposed template does link any of these with the Python shared library, thus it is not going to work.

2024-05-23 16:40 UTC, closed without merging

2024-05-23 16:49 UTC, eli-schwartz commented
> Does it make sense to have a template for building a stand alone executable, a shared library, or a static library with Cython? While it is technically possible, I believe that in 99.9% of the cases, Cython is used to build Python extensions. Anyhow, the `meson.build` proposed template does link any of these with the Python shared library, thus it is not going to work.

I don't think it's very useful for shared or static libraries because a dlopen'ed module is the useful usecase for a library.

Executables I've seen, in particular python scripts that can be optionally compiled via cython's "pure python" mode for speed purposes and have hand-optimized cython types in hot code.