Preserve CMake link lib order
mesonbuild/meson pull request #13287
Opened 2024-06-02 15:34 UTC by dg0yt

Cherry-picked and adapted from https://github.com/microsoft/vcpkg/pull/38658:

Keep order of, and duplicates in, link libraries imported from CMake.
"Traditional" linkers need static libraries given in a particular order (independent libs last).

Sorting in `mesonbuild/cmake/tracetargets.py` was already removed in https://github.com/mesonbuild/meson/commit/05f4e0d6c5e74d5dfc1f1b32ac2ee26af664c950.  
This PR removes another sorting step.

(Order of link libs may still be wrong because `tracetargets.py` doesn't implement visit the target digraph in in topological sort order. This left for another PR.)

2024-06-02 17:34 UTC, eli-schwartz commented
> "Traditional" linkers need static libraries given in a particular order (independent libs last).

Incorrect. Besides, the same linker is used for meson artifacts anyway. ;)

Note that the other commit you linked to was *not* about linkers requiring a specific order for link libs with independent libs last.

> (Order of link libs may still be wrong because `tracetargets.py` doesn't implement visit the target digraph in in topological sort order. This left for another PR.)

Sounds like the exact problem that meson is solving as part of its deduplication, then?

2024-06-02 17:37 UTC, eli-schwartz requested changes
Commit message doesn't explain the problem this is trying to solve.

It seems intuitively this shouldn't be a problem. Can you show the difference in the resulting generated build.ninja after this change is applied? That may help me understand.

2024-06-02 17:44 UTC, dg0yt commented
Are we talking about "incorrect" or "doesn't explain the problem"? It might be possible to overcome the latter, but impossible to overcome the former.

> Sounds like the exact problem that meson is solving as part of its deduplication, then?

Hm, I wonder how a deduplicated, sorted `[ '-lcharset', '-liconv' ]` is formed back into a `-liconv -lcharset` when this is the order needed by the traditional linker.

2024-06-02 18:04 UTC, eli-schwartz commented
Which linker are you talking about.

2024-06-02 19:40 UTC, dg0yt commented
I still struggle to form a mesonish test case because I don't find a good example. (I need two static libs plus cmake config, to be used as direct CMake dependencies. What I have is dependencies handed out by the cmake subproject.)

What I do see is use of `-Wl,--start-group` which is usually said to resolve problems for circuar dependencies, but may also "solve" static link lib order.

2024-06-02 19:57 UTC, eli-schwartz commented
> What I do see is use of `-Wl,--start-group` which is usually said to resolve problems for circuar dependencies, but may also "solve" static link lib order.

static lib link order is a special case of circular dependencies.

The problem is that historically, unix linkers closed out a static archive as soon as they finished processing it (for previously appearing symbols) in order to save memory on very space-constrained systems of old. So if you needed to get symbols required by a later library, from an earlier library, this might work if the symbol was already pulled in somehow, but otherwise it would fail.

For circular dependencies, the "trick" was therefore to list libraries like this:

```
-lfoo -lbar -lfoo -lbar -lfoo -lbar -lfoo -lbar -lfoo -lbar
```

as many times as it takes to fully flatten the dependency cycles. Each time it processes a library, it pulls a couple symbols from the library for use -- those symbols then need one unresolved symbol, which is pulled from the other one, which in turn requires a *new* symbol from the first library, which in turn requires [...]

But it's the same problem if you list `-lcharset -liconv`. In order to refer to symbols from a previous library, you cannot close out the library.

The Microsoft linker does the expected thing, and unix linkers can opt in to the expected thing using --start-group. Meson currently opts in for all grouped libraries in targets produced by meson. I haven't looked at what the cmake subprojects do though -- it is possible it is mishandled there. If it is, then what we really want to do for consistency is to use --start-group.

2024-06-02 20:30 UTC, jpakkane commented
> Keep order of, and duplicates in, link libraries imported from CMake.
> "Traditional" linkers need static libraries given in a particular order (independent libs last).

Yes, but the real world is more complicated. Apple's linker will actually print a warning message if any libraries are duplicated on the link line. We can assume that at some point this will become a hard error.

LLD and MSVC's linkers (I think) work in the "smart" way where libs do not need to be duplicated but instead it will do a global search for symbols. GNU ld seems to be the only linker in common use that works in the "bad old way" and even that can be fixed by removing all duplicates and putting all libs inside a single link group. Embedded linkers might behave differently, I have no experience with those.

I have been meaning to write a blog post about this but have not gotten around to doing it.

2024-06-02 21:37 UTC, dg0yt commented
> I still struggle to form a mesonish test case because I don't find a good example. (I need two static libs plus cmake config, to be used as direct CMake dependencies. ...)

This.

2024-06-04 06:39 UTC, dg0yt commented
The use of groups in unexpected to me, given the documentation for GNU ld and the efforts to maintain order in places outside meson.
Closing now, this was just the most trivial item on the list.

2024-06-04 06:39 UTC, closed without merging

2024-06-05 10:43 UTC, dg0yt commented
FTR I was probably triggered by the sorting/deduplication breaking `-framework CoreFoundation` stuff as in:
~~~
/Library/Developer/CommandLineTools/usr/bin/cc -fPIC -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk -g  -o intl_cmake_t intl_cmake_t.p/intl_t.c.o -L/Users/vcpkg/Data/installed/arm64-osx/debug/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -fuse-ld=/Library/Developer/CommandLineTools/usr/bin/ld -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk -framework /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/libcharset.tbd /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr/lib/libiconv.tbd /Users/vcpkg/Data/installed/arm64-osx/lib/libintl.a CoreFoundation
clang: error: no such file or directory: 'CoreFoundation'
~~~

Which is the missing link to https://github.com/mesonbuild/meson/commit/05f4e0d6c5e74d5dfc1f1b32ac2ee26af664c950, which even added a test but doesn't test a mix of link libs.

Well, the framework topic is on the list already... 
Question: Shall these flags be turned into proper `ExtraFrameworkDependency` objects?

2024-06-05 10:47 UTC, dg0yt commented
> Which is the missing link to [05f4e0d](https://github.com/mesonbuild/meson/commit/05f4e0d6c5e74d5dfc1f1b32ac2ee26af664c950), which even added a test but doesn't test a mix of link libs.

... if it even tests "CMake" at all, https://github.com/dg0yt/meson/pull/3.