cargo: Fall back to the checksum in Cargo.lock metadata table
mesonbuild/meson pull request #13331
Opened 2024-06-16 23:22 UTC by swick

In ansi_term-0.12.1 the packages do not have a checksum entry but it can be found in the global metadata table.

2024-06-16 23:55 UTC, eli-schwartz requested changes

2024-06-16 23:55 UTC, eli-schwartz commented on mesonbuild/cargo/interpreter.py
> +                    checksum = cargolock["metadata"]["checksum {} {} ({})".format(name, version, source)]
Prefer single quotes.

2024-06-17 15:00 UTC, xclaesse commented
I guess that's an older file format? LGTM.

2024-06-17 15:00 UTC, merged

2024-06-17 15:31 UTC, swick commented
No idea really. Just something I ran into when playing around.