Use werror for gnome.generate_gir(fatal_warnings:)
mesonbuild/meson pull request #13464
Opened 2024-07-22 19:31 UTC by tristan957

In addition to the kwarg, Meson will now read werror to determine whether to turn on this warning.

2024-07-22 19:32 UTC, tristan957 commented
cc @ebassi. Saw your introspection talk, so thought I would help you out.

2024-07-24 09:40 UTC, ebassi commented
Yes, this is what I had in mind. There's still the question as to whether we want `fatal_warnings` to override `werror`, i.e. the case where you pass `--werror` but `fatal_warnings: false` should take precedence. I don't have a strong opinion on that regard.

2024-07-24 15:20 UTC, tristan957 commented
Cool. Thanks for your feedback.

2024-07-24 15:24 UTC, eli-schwartz commented
I agree, that fatal_warnings should be updated to track either boolean values from meson.build or default=None as a sentinel for "no value passed in meson.build", so that it can check the global "werror" option only when fatal_warnings is None.

2024-07-24 15:52 UTC, tristan957 commented
Eli, would changing the default not be a breaking change?

2024-07-24 16:04 UTC, eli-schwartz commented
The default is werror=false and `fatal_warnings: false`, so after this PR is implemented, users would still not have fatal warnings unless they somehow opted into it.

Not sure what you mean by that.

2026-08-24 17:39 UTC, tristan957 commented
@eli-schwartz finally got around to your comment. Let me know if there are still problems.

2026-08-24 18:38 UTC, dcbaker requested changes

2026-08-24 18:38 UTC, dcbaker commented on mesonbuild/modules/gnome.py
> +            fatal_warnings = werror
I think we want to avoid the option lookup if we don't need it.

```suggestion
        
        fatal_warnings = kwargs['fatal_warnings']
        if fatal_warnings is None:
            fatal_warnings = state.environment.coredata.get_option(OptionKey('werror', machine=MachineChoice.BUILD, subproject=state.subproject))
```

2026-08-25 05:00 UTC, eli-schwartz approved these changes

2026-08-28 16:58 UTC, merged