Skip broken tests in CI
mesonbuild/meson pull request #13518
Opened 2024-08-06 05:27 UTC by RossComputerGuy

Skips 4 tests in total, these are critical to get the CI Image Builder workflow to run.

- failing: 80 dub library: version of dub is incompatible on OpenSUSE and Ubuntu
- failing: 81 dub executable: version of dub is incompatible on OpenSUSE and Ubuntu
- frameworks: 17 mpi: gfortran tries to use invalid symbols on Ubuntu
- frameworks: 24 libgcrypt: libgcrypt-config does not exist on Arch Linux due to the move to pkg-config

2024-08-06 05:50 UTC, eli-schwartz requested changes

2024-08-06 05:50 UTC, eli-schwartz commented on test cases/failing/80 dub library/test.json
> +  "expect_skip_on_jobname": ["opensuse", "ubuntu-rolling"],
Note the name: "expect_skip". 

Not "skip". This doesn't skip tests, it asserts in CI that if they are skipped, it doesn't constitute "UNEXPECTEDSKIP" status.

2024-08-06 05:53 UTC, eli-schwartz commented
> * failing: 80 dub library: version of dub is incompatible on OpenSUSE and Ubuntu
> 
> * failing: 81 dub executable: version of dub is incompatible on OpenSUSE and Ubuntu

Both fixed by #12143

> * frameworks: 17 mpi: gfortran tries to use invalid symbols on Ubuntu

Why are the symbols invalid?

> * frameworks: 24 libgcrypt: libgcrypt-config does not exist on Arch Linux due to the move to pkg-config

Fixed on July 25 by me, but I had grouped it in with another PR since it needs an image builder run.

2024-08-06 05:57 UTC, RossComputerGuy commented
> Both fixed by https://github.com/mesonbuild/meson/pull/12143

:+1: Was marked as a draft so didn't catch that.

> Why are the symbols invalid?

Because Ubuntu has `MPI_Init` and not `mpi_ini_`, gfortran tries linking to the latter.

> Fixed on July 25 by me, but I had grouped it in with another PR since it needs an image builder run.

:+1:

2024-08-06 05:59 UTC, eli-schwartz commented
> Because Ubuntu has `MPI_Init` and not `mpi_ini_`, gfortran tries linking to the latter.

It would be fantastic if someone could investigate whether Ubuntu needs to change or meson's tests need to change, and get that resolved...

2024-08-06 06:06 UTC, eli-schwartz commented on test cases/failing/80 dub library/test.json
> +  "expect_skip_on_jobname": ["opensuse", "ubuntu-rolling"],
The CI has finished collecting the os_comp jobs now -- this PR causes 7 jobs to fail. e.g

```
 [UNEXRUN]   frameworks: 17 mpi    (method=auto)
Reason: Test ran, but was expected to be skipped for MESON_CI_JOBNAME 'linux-ubuntu-rolling-clang'
 [UNEXRUN]   frameworks: 17 mpi    (method=config-tool)
Reason: Test ran, but was expected to be skipped for MESON_CI_JOBNAME 'linux-ubuntu-rolling-clang'
 [UNEXRUN]   frameworks: 17 mpi    (method=pkg-config)
Reason: Test ran, but was expected to be skipped for MESON_CI_JOBNAME 'linux-ubuntu-rolling-clang'
```

```
 [UNEXRUN]   frameworks: 24 libgcrypt
Reason: Test ran, but was expected to be skipped for MESON_CI_JOBNAME 'linux-arch-gcc'
```

2025-03-07 14:25 UTC, bonzini commented
This PR is now obsolete.

2025-03-07 14:25 UTC, closed without merging