Remove mention of running ninja directly
mesonbuild/meson pull request #13546
Opened 2024-08-15 12:18 UTC by reftel

It may be true that if one uses a Meson version that is more than 4 years old, one might need to run `ninja` directly, but details like that should be safe to keep out of the simple getting started guide.

2024-08-15 12:35 UTC, eli-schwartz requested changes
Actually I strongly disagree and think that ninja should always be used specifically, no matter how new meson is, except specifically when using MSVC due to this bug: https://github.com/ninja-build/ninja/issues/1610

`meson compile` is badly designed and cannot be fixed without breaking existing users.

But I appear to be in the minority about thinking this...

2024-08-15 14:45 UTC, dcbaker commented
I agree with @eli-schwartz, I wish I'd never written `meson compile`. I had hoped for something that could be used in cases where compatibility was more important than feature richness, like in CI's where people basically wanted `build, use X cores, test`.

2024-12-31 17:44 UTC, bonzini commented
@dcbaker it would be nice to have a comment about the problems with `meson compile` in either the docs or `mcompile.py`. Otherwise a PR like this one seems like an obvious idea.

2025-01-02 17:47 UTC, dcbaker commented
@bonzini I'm not sure I can write that in a neutral voice. My feeling is pretty strongly "This simple tool I wrote for allowing people to abstract a small number of common arguments between various backends gained a bunch of features I said during review was a bad idea and shouldn't land but did anyway and has become bad, please don't use it", and that's not really something I can put in the docs or in mcompile.py

2025-03-07 14:27 UTC, bonzini commented
In any case, this can be closed as not planned.

2025-03-07 14:27 UTC, closed without merging