android: Added android_usecase kwargs to executable
mesonbuild/meson pull request #13767
Opened 2024-10-08 23:04 UTC by sp1ritCS

This is the idea I've came up with in regards to https://github.com/mesonbuild/meson/discussions/13758

---

By setting android_usecase to `application`, the executable gets actually built as a shared library instead of an executable. This makes it possible to use an application within an android application process.

https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7555/

2024-10-13 20:29 UTC, jpakkane commented
Could you not already do this with [the `build_target` function](https://mesonbuild.com/Reference-manual_functions.html#build_target)?

2024-10-13 21:10 UTC, sp1ritCS commented
Perhaps. However my goal is to have a [builder tool](https://github.com/sp1ritCS/gtk-android-builder/blob/master/pixiewood) that you can just point at a meson project to create an apk from.

While you still have to modify your meson sources and to add the android_usecase, it seems less invasive than doing having users switch their excecutables to `build_target(target_type: host_machine.os() == android ? 'shared_module' : 'executable', ...)`, especially given that they will have to add the android glue dependency too (declaring a link_whole dependency with it and adding it does seem to work within meson, not sure why cmake didn't like it)

What about adding a `excecutable` function to the gnome module that has the same prototype as a normal executable but that creates a library linked against the glue dependency if host_machine == 'android'?

2025-03-05 16:15 UTC, jpakkane commented
Since you seem to have knowledge about this could you answer some questions I have about this?

How are Android applications actually done? FWICT it used to be the case that you could not have actual executables, instead it needed to be a shared library which you then opened from the Java side with whatever the equivalent of `dlopen` is. Can you now have actual executables? Can there be several? Can you invoke many processes within your sandbox? Is it possible (and if yes, do you intend to use) to make an Android application that is just native code without any Java/JVM?

2025-03-05 17:24 UTC, sp1ritCS commented
It was always possible to have actual 'executables' on Android. Its just Linux after all and `/system/bin/` contains a bunch of them the system relies on to work.

The thing is that users usually don't interact with them directly (outside of developers using `adb shell`) and executables do not have the possibility of interacting with the Android system (unless they [use private non-stable interfaces](https://github.com/Bzi-Han/AndroidSurfaceImgui/blob/main/modules/ANativeWindowCreator.h)), it is however possible for Applications to do the pipe+fork+exec combo to execute their own executables as child process. Doing so is discouraged however, with Google increasingly limiting its possibilities ([phantom process killer](https://issuetracker.google.com/issues/205156966), [SELinux rules that enfore R^X for exec](https://issuetracker.google.com/issues/128554619)). [Termux](https://termux.dev/) however makes heavy use of fork+exec to provide a POSIX like shell experience and is relatively popular as it allows you to use full SSH/tmux/vim/... on Android.

> Is it possible (and if yes, do you intend to use) to make an Android application that is just native code without any Java/JVM?

No, you can make executables not applications. Applications are still special (Zygote) and need Java (ART) to interact with the stable OS interfaces provided.

My work of porting GTK to Android proper, needs an "Application" to work with and essentially works by having glue expose the proper JNI symbol and then [calls `main()`](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/android/glue/glue.c?ref_type=heads#L117) from the actual codebase in a new thread.

2025-03-05 18:21 UTC, bruchar1 commented
Why don't you simply add a user option or a property to the cross file, and use it for the target type?

2025-03-05 18:49 UTC, sp1ritCS commented
> Why don't you simply add a user option or a property to the cross file, and use it for the target type?

My idea was need as little changes as possible to the meson files of existing applications and this was just my initial attempt. A better (but gtk specific solution) is proposed in #13800. It cuts down the currently needed `build_target(host_machine.system() == 'android' ? 'shared_library' : 'executable', '...', dependencies: [...] + host_machine.system() == 'android' ? dependency('gtk4-android') : [], ...)` to `import('gnome').executable(..., dependencies: [...], ...)`

2025-03-06 15:13 UTC, jpakkane commented
So, basically, the actual thing that you need to get is "build this target as an executable on all other platforms, but as a shared library in Android"? Are there any other use cases that need to be covered?

If true, then this could be implemented in one of several ways:

- tell people to use `build_target` and set the target type manually
- add some sort of module, custom function, etc that does the above
- add this (or some similar) kwarg to handle the issue
- something else, what?

The kwarg in this MR is similar to how `win_subsystem` works which is good for consistency.

2025-03-07 12:24 UTC, sp1ritCS commented
> Are there any other use cases that need to be covered?

There should be some mechanism that link-wholes a glue library (that provides the JNI entry function symbol) into the shared library. The idea I had originally for this MR was to have the ability to specify the dependency name in the cross file, but I didn't really look into how to implement it specifically. Obv. the alternative GNOME/GTK specific PR doesn't need that as it can just lookup the `gtk4-android-glue` dependency directly (for now).

> The kwarg in this MR is similar to how win_subsystem works which is good for consistency.

That was the idea behind it :)

2025-04-13 10:37 UTC, jpakkane commented
I'm not very fond of the name `android_usecase`. It is not very descriptive, though I have problems trying to come up with a better name (as is usually the case). `android_exe` is similarly poor.  `android_executable_type` is too long. Does `android_exe_type` sound good for people?

2025-04-13 20:41 UTC, sp1ritCS commented
Sure, `android_exe_type` is fine too.

About the issue of needing to include glue code: I've taken a closer look at how QT does it, and it looks like they initialize themselves in the `JNI_OnLoad` of the libqt and the libqtandroid plugin and to launch the actual user code they require the shared library name containing the application main() to be specified in the ApplicationManifest.xml with a `<meta-data>` tag. [They then load the application shared library using dlopen/dlsym to run the main function](https://github.com/qt/qtbase/blob/ce38df4461d09793de675b6161225fc86e5168f4/src/plugins/platforms/android/androidjnimain.cpp#L381). This way no glue code is needed on the application side.

I think I should be able to implement a similar mechanism for GTK, which means the the changes of this MR would be enough to make it acceptably work. The downsides of this however would be:
- Less logical ordering: GTK is going to be responsible to be loading the application which itself is going to use GTK.
- Using dlopen/dlsym is going to be more error prone instead of letting the linker do it for you (and any issues will only be detected at runtime)
- Unlike statically linking the glue code will call main into the application, it must be made sure that the `main` symbol will actually be exported, which isn't the case by default if people have `add_project_arguments('-fvisibility=hidden', ...])`. (This should be able to be remedied by modifying the cross file to add a linker script)

2025-04-14 14:45 UTC, jpakkane commented
Assuming we merge this can the listed issues be fixed later once they actually come up without breaking bw compatibility with this change?

2025-04-14 15:13 UTC, sp1ritCS commented
The only *real* issue that can be fixed is the one about the hidden main symbol (the other ones are more "technical limitations" one has to live with).

The hidden main symbol should be fixed however (as the problem will be encountered immediately due to the gtk4-demo) because adding `android_exe_type` to meson - that just makes built applications useless because they don't provide any symbols doesn't - make much sense.

I've wondered if it may be possible to generate and add with `-include` a header that declares the main() function with visibility default. The issue with that is, that is somehow has to cope with `main(void)`, `main(int argc, char **argv)` and `main(int argc, char **argv, char **envp)`.

2025-04-14 16:04 UTC, jpakkane commented
Can the change be done basically with this:

```
#ifdef __ANDROID__
__attribute__((visibility("default")))
#endif
int main(...) {
    ...
```

If yes, this seems like the simplest solution.

2025-04-14 16:55 UTC, sp1ritCS commented
Sure that'd work too (realistically the __ANDROID__ isn't even needed), but it would that require affected users update their code.

2025-04-16 09:33 UTC, jpakkane commented on run_project_tests.py
> +        TestCategory('platform-android', 'android', not mesonlib.is_android()),
This will never actually run. `is_android` means "is the machine I'm currently running on an Android machine", which would only be true when running on an Android device and most (all?) builds for Android are done by cross compilation. I don't think we have the Android NDK installed on any CI machines either so the test could not be run in any case.

2025-04-16 10:57 UTC, jpakkane commented on run_project_tests.py
> +        TestCategory('platform-android', 'android', not mesonlib.is_android()),
Maybe just add a comment like:

    # FIXME, does not actually run in CI, change to run the test if an Android cross toolchain is detected.

2025-04-16 13:42 UTC, sp1ritCS commented
Sure, that might work too. It would however require us to strip **any** executable specific kwargs (gui_app, win_subsystem, export_dynamic?), not just android_exe_type, as shared_library would complain about it otherwise

2025-04-16 16:11 UTC, dcbaker requested changes

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/interpreter/type_checking.py
> +        validator=_validate_android_exe_type,
```suggestion
        validator=in_set_validator({'application', 'executable'}),
```
and drop the hand rolled validator.

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/interpreter/kwargs.py
> +    android_exe_type: T.Optional[str]
```suggestion
    android_exe_type: T.Optional[Literal['application', 'executable']]
```

This can later propagate down to help catch typos

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/interpreter/interpreter.py
> +                        'Executable got both "gui_app", and "win_subsystem"/"android_exe_type" arguments, which are mutually exclusive',
```suggestion
                        'Executable got both "gui_app" and at least one of: "win_subsystem" or "android_exe_type" arguments, which are mutually exclusive',
```

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/build.py
> +            self.filename = self.prefix + self.filename
This seems unrelated?

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/backend/ninjabackend.py
> +                    commands += linker.get_pie_link_args()
```suggestion
            elif target.pie:
                commands += linker.get_pie_link_args()
```

2025-04-16 16:11 UTC, dcbaker commented on docs/yaml/functions/executable.yaml
> +    since: 1.6.0
```suggestion
    since: 1.8.0
```

2025-04-16 16:11 UTC, dcbaker commented on mesonbuild/interpreter/type_checking.py
> +        (str, NoneType),
This also needs: `since='1.8.9'`

2025-04-16 16:15 UTC, sp1ritCS commented on mesonbuild/build.py
> +            self.filename = self.prefix + self.filename
this was required for the 'lib' prefix

2025-04-16 17:22 UTC, dcbaker commented
that assert needs to be `None` aware `t is not None or t in {...}`

And please do use the set, the python byte compiler can do some optimization around that which makes the lookup faster.

2025-04-16 17:23 UTC, dcbaker approved these changes
Thanks for making those changes, with the CI turned green this looks good to me.

2025-04-16 17:36 UTC, sp1ritCS commented
@dcbaker I've seen that. I'm just wondering why its necessary, given that `interpreter.py` should set android_exe_wrapper if it isn't set.

2025-04-16 18:03 UTC, jpakkane commented
```
   File "/__w/meson/meson/mesonbuild/build.py", line 1999, in __init__
    assert kwargs.get('android_exe_type') in ['application', 'executable']
AssertionError
```

If the key is not in dict, `.get` returns `None`.

2025-04-16 19:24 UTC, jpakkane commented
In case this won't be ready for rc1, it can be merged after that.

2025-04-16 20:24 UTC, sp1ritCS commented
> In case this won't be ready for rc1, it can be merged after that.

whats the release schedule like? Any chance I can get #13854 looked at before release? I could work around it (by running meson subprojects update before invoking meson) but it be nicer if I didn't and could save myself from downloading subprojects that I don't need to to my configure options / platform.

2025-04-17 16:01 UTC, merged

2025-04-17 16:10 UTC, eli-schwartz commented
> > In case this won't be ready for rc1, it can be merged after that.
> 
> whats the release schedule like? Any chance I can get #13854 looked at before release? I could work around it (by running `meson subprojects update` before invoking meson) but it be nicer if I didn't and could save myself from downloading subprojects that I don't need to to my configure options / platform.

Release freeze starts when rc1 is tagged and published. Roughly ~weekly release candidates until we are happy with the results and ready for final release. Only bugfixes and documentation changes allowed for the most part, new features need an explicit Release Freeze exemption from @jpakkane.

That PR you linked may be safe to backport though, even if it misses the final release.