interpreterbase: Add disabler exception for `get_variable` method
mesonbuild/meson pull request #13777
Opened 2024-10-11 15:50 UTC by amcn

Add an exception to the disabler check to allow objects with a `get_variable` method to not always pick a disabler if their arguments contain one. This mimics the behaviour already in place for calls to function, which has a set of excepted functions.

Fixes #13717

2024-10-12 04:38 UTC, amcn commented
I've been unable to reproduce locally the test failure that can be observed in the CI pipeline and I don't seem to be able to manually trigger it so I'm going to force push to rerun the CI in the hope that it's a sporadic failure. Apologies for the noise.

2024-10-12 08:06 UTC, amcn commented
So it seems that the failure in the Ubuntu cross-arm CI was in fact sporadic as it seems to have disappeared upon re-execution of the CI pipelines. It seems however that the Azure CI has now failed. Please correct me if I am wrong but it seems that this failure is due to the tests exceeding their allotted execution time. Is there a way to avoid such failures?

2024-11-20 07:02 UTC, eli-schwartz requested changes
Maybe it would make sense to include this test case inside of `common/158 disabler/`?

2024-12-31 17:38 UTC, bonzini commented
Probably worth adding a release note.

I added it to the 1.7 milestone because it's almost ready and because there's no 1.8 milestone in the project, but it's probably a bit late.

2025-01-01 13:02 UTC, amcn commented
In principle I'm not against a release note but from what I gather release notes are mostly for new features or behavioural changes which users might need to be made aware of, whereas this PR is a relatively small bugfix. Is there an important behavioural change that I am not considering?

2025-01-06 14:46 UTC, bonzini approved these changes
The changes requested by @eli-schwartz were made correctly.

This is technically a backwards incompatible change so the bar for requiring a release note may be lower. If so feel free to apply and I can write the release note on top before the release.

2025-01-06 17:06 UTC, eli-schwartz commented
I guess it depends on how you define a backwards incompatible change. Any change to observable behavior is backwards incompatible if someone was relying on the previous behavior, but people usually distinguish between bug-for-bug compatibility versus compatibility with expected behavior.

In this case, get_variable used to return a disabler if any of 3 things are true:
- the gotten variable value was a disabler. get_variable returns the gotten variable as specified, and needs no fixing
- the first argument (string value to look up as a varname) is a disabler. This makes no sense conceptually for anyone to ever do, at least as an inline value?
- the fallback value was a disabler, so the get_variable() method call never ran

The PR is intended to ***fix*** the third case, and only the third case, using the rationale that anyone who wrote a fallback disabler intended to run the get_variable method and it was a bug not to do that. It changes behavior for both the second and third cases.

Second case now fails typechecks:
```
meson.build:160:25: ERROR: subproject.get_variable argument 1 was of type "Disabler" but should have been "str"
```

"Arguably this is correct, since it is improper usage of the function to pass a disabler." But hmm, is it really? It's legal to pass `get_variable(disabler(), var_true)` and it yields a disabler. We have test coverage for that precise case. It is specially handled by allowing Disabler objects in typed_pos_args, and the first thing the function does is an isinstance check for Disabler:

https://github.com/mesonbuild/meson/blob/631cce71db8dbae9f2330d48cb429a7ccec77135/mesonbuild/interpreter/interpreter.py#L3525-L3533


That may be a bug in the implementation of this PR. But as far as release notes go, if we only change the third case then I can't see how any backwards compatibility breaks occur. One possible nuance however is that it might be worth adding a FeatureNew to tell people that this "now works", because if you use it and specify a `meson_version: '>=1.2.0'` your build actually "doesn't work" on older meson versions.

2025-01-19 18:59 UTC, merged

2025-01-19 20:11 UTC, eli-schwartz commented
@jpakkane did you not see the part where my review suggested that this PR has a bug in its implementation?

2025-01-19 20:18 UTC, jpakkane commented
I did not, so that's my bad then. I'll open a revert MR that we can merge before the release if it can't be proven that a bug does not exist (or it is fixed properly).