Reimplement several methods for Fortran compilers
mesonbuild/meson pull request #13815
Opened 2024-10-23 10:57 UTC by svillemot

The output_is_64bit, sizeof, cross_sizeof, compute_int and cross_compute_int methods are reimplemented for Fortran compilers. Those inherited from CLikeCompiler do not work since they assume C or C++.

Note that those tests rely on Fortran 2008 features (notably the c_sizeof operator).

Closes #12757

2024-10-23 12:24 UTC, svillemot commented
There is some code duplication, especially the `cross_compute_int` method which is almost identical. Don’t know whether you want to factorize it (the only difference is the logical operator `&&` which is replaced by `.and.` in Fortran).

2024-10-25 19:29 UTC, dcbaker approved these changes
I'm okay with duplication here, though we could break the expressions out into some sort of class variable if you're feeling adventurous and just really want to do that.

2024-10-25 19:30 UTC, dcbaker requested changes
Sorry, one small request. Could you add a release snippet about these methods being correctly implemented for Fortran? Having this documented would be good I think.

2024-10-26 16:20 UTC, svillemot commented
@dcbaker Thanks for the review. I added a release snippet.

2024-10-27 03:00 UTC, dcbaker approved these changes
Thanks, looks great!

2024-10-27 03:00 UTC, merged