fix missing extension in command path
mesonbuild/meson pull request #13901
Opened 2024-11-12 20:42 UTC by bruchar1

On Windows, if the native file contains a path without the extension, the executable may be found, but custom target would fail because that path does not exist.

2024-11-12 20:54 UTC, eli-schwartz requested changes

2024-11-12 20:54 UTC, eli-schwartz commented on mesonbuild/programs.py
> +                                break
Since this is copied from search_windows_special_cases you should include the comment from there as well.

2024-12-31 17:35 UTC, bonzini commented
Can you add a test case?

2025-01-06 12:44 UTC, bruchar1 commented
> Can you add a test case?

I think that would be difficult, as it would need the absolute path to a know executable on the system. I'm not sure it worth the effort.

2025-01-07 19:37 UTC, merged