dependencies/dev: prepend sysroot when searching for GTest sources
mesonbuild/meson pull request #13934
Opened 2024-11-20 13:12 UTC by rossburton

Don't hardcode paths in /usr when looking for the GTest sources, as in cross-compile or other builds with a sysroot this will find the host sources, not ones that we want to use in the sysroot.

Closes #12690.

2025-02-18 14:01 UTC, bruchar1 approved these changes

2025-02-27 20:34 UTC, eli-schwartz requested changes
This seems reasonable enough, small nit though.

2025-02-27 20:34 UTC, eli-schwartz commented on mesonbuild/dependencies/dev.py
> +        self.src_dirs = [sysroot + '/usr/src/gtest/src', sysroot + '/usr/src/googletest/googletest/src']
Inconsistent quoting style, consolidate on single quotes as used elsewhere.

2025-02-27 20:37 UTC, rossburton commented on mesonbuild/dependencies/dev.py
> +        self.src_dirs = [sysroot + '/usr/src/gtest/src', sysroot + '/usr/src/googletest/googletest/src']
Apologies, my double-quote muscle memory is strong. I find writing meson.build files quite painful :)

2025-03-24 04:39 UTC, merged