Allow custom target output to be processed by generators
mesonbuild/meson pull request #8198
Opened 2021-01-14 02:54 UTC by ximion

Hi!
This change permits a `generator` to consume outputs by `custom_target` instead of failing.
This is needed to fix issues like #5693 where a generator created by the Qt module needs to process data that itself was produced in a custom target.

2021-01-14 17:01 UTC, dcbaker requested changes
I've got a few inline comments, but additionally this needs:
 - a release snippet
 - in the interpreter you need to check for `CustomTarget` and `CustomTargetIndex` inputs, and raise a `FeatureNew` for those. you can look at the implementation of `add_install_script` to see one approach for that.

2021-01-14 17:01 UTC, dcbaker commented on test cases/common/106 generatorcustom/meson.build
> +hs = gen.process('res1.txt', 'res2.txt', res3)
You should add a test for a `CustomTargetIndex` as well, something like `hs2 = gen.process('res1.txt', 'res2.txt', res3[0])` is probably sufficient.

2021-01-14 17:42 UTC, ximion commented on mesonbuild/build.py
> +                        raise InvalidArguments('When using preserve_path_from, all input files must be in a subdirectory of the given dir.')
Not sure if I understood that correctly - I prefixed the error message now, was that the intent of your message? (This one has been in the code like that before)

2021-01-15 00:48 UTC, ximion commented
I made the requested changes now.

2021-01-15 00:48 UTC, ximion commented
I made the requested changes now :-)

2021-01-15 17:24 UTC, dcbaker approved these changes
Thanks for making the changes I requested. This looks good code wise, though the CI failures look relevant.

2021-01-15 19:22 UTC, ximion commented
@dcbaker I looked at the CI issue, and apparently on windows a different working directory is assumed than when running with the Ninja backend on other platforms. I changed the generator code to set the same working directory explicitly on all platforms, so this should work now (still waiting for the CI to confirm that theory ^^).

2021-01-18 02:19 UTC, ximion commented
Okay, I give up with this MSBuild/VisualStudio stuff - I can't test this locally (no Windows...) and I have tortured the CI enough now. It would be very appreciated if someone who knows this backend could have a look at it.
Proper "targets" for the generator are created, but for some reason they are not selected to run:
```
The project "gen-res3@cus" is not selected for building in solution configuration "debug|x64".
The project "gen-res4@cus" is not selected for building in solution configuration "debug|x64".
```
Yet, those targets do advertise the output path, with the current PR even as full path: `D:\a\1\s\b 8e9033c5c6\res3.txt`
But since the generating custom-target isn't run by the generator, of course at build-time the respective file doesn't exist and the build fails.

It kind of looks like the generator --> custom-target dependency is not registered properly with the VisualStudio backend, but I have no idea how to fix that. The Ninja backend has some logic for that which the VisualStudio backend seems to be missing, but I am not 100% how dependencies are actually defined in the VS backend, so that may be the wrong idea.

2021-01-21 22:13 UTC, ximion commented
Is there any resident VisualStudio expert that could have a look at this? It's not unlikely that the more usecases than just this one were actually broken with this backend than noticed before, as it apparently didn't handle explicit generator depends as well before...

2021-01-30 10:05 UTC, jpakkane commented
> but I am not 100% how dependencies are actually defined in the VS backend, so that may be the wrong idea

Inter-project dependencies are defined in each individual target's `vcxproj` file. Here is an example:

```
<ItemGroup>
	<ProjectReference Include=".\mylib@sha.vcxproj">
		<Project>{71FA410B-E276-4CB3-BF79-7C58975A7E3B}</Project>
		<LinkLibraryDependencies>false</LinkLibraryDependencies>
	</ProjectReference>
</ItemGroup>
```

The `Project` entry refers to the target's GUID.

2021-02-01 04:23 UTC, ximion commented
@jpakkane I tried to add this to the VS backend for generator depends (it's clearly missing, so this was a bug even before this testcase accidentally triggered it), but unfortunately this does not appear to make any difference. But I also have no idea about VS project definitions and don't have access to a machine to test this.
Could you maybe have a look at this code? (Potentially there's something obvious that I missed)

2021-02-25 03:04 UTC, ximion commented
I've made it work with some changes to the VS backend, but I am really not knowledgeable in this area (so, I don't know if I did this correctly). At least all tests seem to pass reliably now though :-)

2021-02-25 11:29 UTC, ximion commented
I edited my change from yesterday a bit more, and I am now fairly confident that this is the correct solution. There's no more special-casing, and dependencies of generated sources and generators are read correctly now and added to the build selection when VisualStudio is used as backend.
So, once the tests passed again I think this change would be ready :-)

2021-02-25 18:53 UTC, merged