install_man locale support
mesonbuild/meson pull request #8398
Opened 2021-02-22 04:49 UTC by jaos

Rather than having to manually build the locale aware man paths with

`install_data('foo.fr.1', install_dir: join_paths(get_option('mandir'), 'fr', 'man1'), rename: 'foo.1')`

Support doing

`install_man('foo.fr.1', locale: 'fr')`

2021-02-23 19:46 UTC, jpakkane commented
Is the file name always of the type `foo.fr.number`? That is, could we just detect that and always do the right thing without the user needing to add kwargs by hand?

2021-02-23 21:37 UTC, jaos commented
> Is the file name always of the type `foo.fr.number`? That is, could we just detect that and always do the right thing without the user needing to add kwargs by hand?

I'm not sure. As far as I know there is not an obvious, universal convention. I've had translations given to me with locale name in the file but I have seen other translation projects that keep them in a source directory structure with the locale represented that way. 

Auto detection seems haphazard but we might be able to check against a list. The locale py module does not seem to have an exhaustive list via locale_alias, however.

2021-02-26 17:40 UTC, dcbaker commented
Could we do something like "if you don't set locale and your file ends in `.[str][str].section` we'll guess for you", but an explicit `locale` always overrides?

2021-02-26 17:42 UTC, dcbaker commented
I'm going to be doing some work here, so I could implement the guess mechanism myself if you think it's reasonable, and we could just merge this as-is?

2021-02-26 19:56 UTC, jaos commented
Auto detecting locals might work if you are able to account for all possible formats. 

https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html

It would be nice if there was something to leverage here so we don't get it wrong. Otherwise requiring it be specified seems the most deterministic approach.

2021-02-26 19:58 UTC, jaos commented
> I'm going to be doing some work here, so I could implement the guess mechanism myself if you think it's reasonable, and we could just merge this as-is?

Feel free to incorporate this or a similar approach as you see fit. I really only meant to get the conversation started, not necessarily propose a specific solution.

2021-02-26 23:23 UTC, dcbaker commented
Hmm, we could do something naïve, but I'm okay with starting with an explicit mechanism and adding an implicit one later.

2021-02-26 23:24 UTC, dcbaker approved these changes
The only thing that this needs is a replease note in docs/markdown/snippets

2021-02-26 23:25 UTC, dcbaker requested changes
Oops, clicked the wrong box, sorry.

2021-02-27 00:06 UTC, jaos commented
> The only thing that this needs is a replease note in docs/markdown/snippets

Ok, added docs/markdown/snippets/install_man_locale.md.

2021-02-27 00:11 UTC, dcbaker approved these changes

2021-02-27 00:12 UTC, dcbaker commented
thanks looks good to me.

2021-02-27 12:35 UTC, merged