compilers: clang-cl: Also accept .s files
mesonbuild/meson pull request #8520
Opened 2021-03-11 04:03 UTC by scott-ph

clang-cl has support for gas-compatible assembly files.

2021-03-11 17:55 UTC, dcbaker requested changes
Hey Scott! can you enable clang-cl in `tests/common/128` so we can get some test coverage for this? Otherwise this looks good.

2021-03-11 23:31 UTC, scott-ph commented
> Hey Scott! can you enable clang-cl in `tests/common/128` so we can get some test coverage for this? Otherwise this looks good.

yo @dcbaker! it's been a while. I took a crack at enabling the test and it wound up being a bit ugly. Let me know if you have any suggestions

2021-03-12 23:22 UTC, dcbaker approved these changes
LGTM, thanks!

2021-03-12 23:22 UTC, dcbaker commented
I kicked the CI, so lets see if it'll turn green.

2021-03-13 12:22 UTC, jpakkane commented
This ... makes no sense. Two tests test_dist_git and test_command_line fail with this:

    ../../../../c/Users/VSSADM~1/AppData/Local/Temp/tmpo9fl_peu/meson.build:1:0: ERROR: Unable to detect linker for compiler "cc -Wl,--version"

But in an environment where clang-cl is not even available (as far as I know). The test does pass for other MRs so this does seem relevant.

2021-03-23 21:54 UTC, jpakkane commented
Maybe it was just Cygwin being sporadic. Please rebase to run the tests again.

2021-03-24 10:43 UTC, jpakkane commented
Cygwin failure is unrelated so merging. Thanks.

2021-03-24 10:43 UTC, merged