ninjabackend.py: Implement `link_whole:` for pre-VS2015
mesonbuild/meson pull request #8802
Opened 2021-05-26 09:03 UTC by fanc999

...Update 2, to be exact, since the Visual Studio linker only gained the
`/WHOLEARCHIVE:` feature since Visual Studio 2015 Update 2.

This checks whether we have the corresponding `cl.exe` which is
versioned at or after Visual Studio 2015 Update 2 before we try to apply
the `/WHOLEARCHIVE:xxx` linker flag.  If we aren't, use built-in methods
in Meson to grab the object files of the dependent static lib's, along
with the objects that were `link_whole:`'ed into them, and feed this
list into the linker instead.

This would make `link_whole:` work on Visual Studio 2015 Update 1 and
earlier, including previous Visual Studio versions.

With blessings, thank you!

2021-05-26 17:00 UTC, dcbaker requested changes
This looks good to me, I've got one small suggestion to use a base class for the check, and then it looks like there's two test cases you need to modify to enable them:
- common/137 whole archive
- common/170 generator link whole

2021-05-27 04:25 UTC, fanc999 commented on mesonbuild/backend/ninjabackend.py
> +            objects_from_static_libs = []
Done the changes :)

2021-05-27 16:54 UTC, dcbaker approved these changes

2021-05-27 16:54 UTC, dcbaker commented
Looks good, thanks!

2021-05-27 16:54 UTC, merged