Again some Xcode fixes
mesonbuild/meson pull request #9141
Opened 2021-08-20 16:58 UTC by jpakkane

A few regressions and minor tweaks. Can now build [Godot](https://github.com/godotengine/godot/pull/51153).

We should probably consider adding some sort of a CI for the Xcode backend. Sadly it is incredibly slow and not all of the test suite works with it yet (and there does not seem to be many volunteers around to fix it).

2021-08-20 17:53 UTC, dcbaker commented
I'm planning to start adding type annotations to the backends now that the core backend annotations are in. If we were serious about getting a CI build going i can help fix bugs.

2021-08-20 17:58 UTC, dcbaker requested changes
Overall looks reasonable, i have a few implementation suggestions, but otherwise I'm good with this.

2021-08-20 17:58 UTC, dcbaker commented on mesonbuild/backend/xcodebackend.py
> +        return key in self.keys
This isn't very idiomatic python. Why not implement a `__contains__` dunder method?

2021-08-20 17:58 UTC, dcbaker commented on mesonbuild/backend/backends.py
> +                    fname = [os.path.join(self.get_target_private_dir(i.target), p) for p in outputs]
This really feels like a layering violation. Maybe we need a separate method that the xcode backend can override?

2021-08-21 00:31 UTC, dcbaker approved these changes

2021-08-21 19:33 UTC, jpakkane commented
Test failure is unrelated and did pass on all the other test runs.

2021-08-21 19:33 UTC, merged