More typed_kwargs for the gnome module
mesonbuild/meson pull request #9594
Opened 2021-11-18 19:05 UTC by dcbaker

This is a smaller follow up to the last set of cleanups to the gnome module with conversions to `typed_kwargs`. There are only two functions covered here, genmarshal and generate_vapi. Again, this allows a number of nice cleanups. In addition I noticed that genmarshal still exposes `build_always` without deprecation. I've made that deprecated, and added the `build_always_stale` and `build_by_default` keyword arguments matching the behavior of `custom_target`.

2021-11-18 19:35 UTC, dcbaker commented
The `lgtm` warning makes no sense, it thinks a function returning a tuple of 5 elements returns 4, then complains about it.

2021-12-07 04:10 UTC, eli-schwartz requested changes

2021-12-07 04:10 UTC, eli-schwartz commented on mesonbuild/modules/gnome.py
> +        KwargInfo('build_always', bool, default=False),
There's a bunch of mysterious kwargs here, that are not in the documentation *and* are not in permittedKwargs. Attempting to use them raises a fatal error, e.g. 

```
genmarshal/meson.build:1:0: ERROR: Got unknown keyword arguments "build_always"
```

In commit 80d665e8decd644d737930d450f0bc66d6b5b02c, we added that error checking in, by following the documentation. At the time, the error message would be:

```
Meson encountered an error in file genmarshal/meson.build, line 1, column 0:
Invalid keyword argument build_always.
```

We also have some terrible manual argument checking in known_kwargs and known_custom_target_kwargs, but they've been entirely overridden for 4.5 years now, and no one has ever complained that they need these undocumented kwargs, which, again, were undocumented.

I see no grounds to re-add support for them half a decade later, especially just to mark at least one of them as deprecated in a later commit in the same PR... and if any of them do get added, I want them to be documented.

2021-12-07 19:45 UTC, eli-schwartz approved these changes

2021-12-07 21:12 UTC, merged