i18n: Add support for joining XML localization via itstool
mesonbuild/meson pull request #9742
Opened 2021-12-18 03:06 UTC by ximion

Hi!

This PR adds support for the "join" feature of `itstool` to Meson. While (x)gettext can merge XML, when working with AppStream metadata I found out that it is pretty unpredictable in how data is merged, especially when inline tags are involved. At the very least, inline markup gets XML-escaped, and I found no way at all to work around this particular issue.
[Itstool](http://itstool.org/) however always generates correct results and obeys the rules defined in ITS files properly. This tool is also very widespread and available in every Linux distribution I checked. It also is used by GNOME's help.

Using `itstool` from Meson is pretty cumbersome at the moment, as you need to scrape through the output generated from `i18n.gettext()` and rename mo files so itstool can infer locale names.
This is admittedly a bit dumb, but there's also no real way around this (even if itstool gained support to specify per-file locale on the command line, it would take ages before the changes are widespread enough to be used unconditionally).
The new code comes with a pretty realistic example of how this feature will likely be used in Meson as unit test.

If `itstool_join` is called we fail if the tool could not be found (as opposed to `merge_file`). I chose this behavior because a silent failure would mean crucial data may not get installed, and even if it was installed would be untranslated which explicitly was not the intent of the developer when the join command is used.
Besides that, I don't think there's anything else particularly noteworthy about this change.

Thanks for considering!

2021-12-18 08:47 UTC, ximion commented
Looks like on bionic, itstool does not generate the expected output - I'll try to reproduce that locally to see what's going on there (and either fix the issue or add a smarter test).

2021-12-18 17:29 UTC, ximion commented
That bionic build failure was caused by an older itstool version which did not read custom ITS files correctly while joining. I adjusted the test to pass even if we have an older itstool which has that bug.

2021-12-30 12:50 UTC, jpakkane requested changes

2021-12-30 12:50 UTC, jpakkane commented on test cases/frameworks/6 gettext/data3/meson.build
> +  install_dir: join_paths(get_option('datadir'), 'metainfo'),
This is old-style code, the modern equivalent should be `get_option('datadir') / 'metainfo'`.

2021-12-30 12:50 UTC, jpakkane commented on test cases/frameworks/6 gettext/data3/meson.build
> +  grep_exe = find_program('grep')
This is _not_ acceptable. Any use of shell tools is absolutely prohibited as all tests must run on a bog standard Windows `cmd.exe` without any unixy stuff. This should be a standalone Python script that reads the result file and validates it.

2021-12-30 12:50 UTC, jpakkane commented on test cases/frameworks/6 gettext/data3/meson.build
> +    install_dir: join_paths(get_option('datadir'), 'metainfo'))
This should use `/` as well.

2021-12-30 14:10 UTC, eli-schwartz commented
> Using `itstool` from Meson is pretty cumbersome at the moment, as you need to scrape through the output generated from `i18n.gettext()` and rename mo files so itstool can infer locale names.
This is admittedly a bit dumb, but there's also no real way around this (even if itstool gained support to specify per-file locale on the command line, it would take ages before the changes are widespread enough to be used unconditionally).

It will take even longer if no one ever pushes to have this changed, so it never gets implemented. If we are going to handle this I'd vastly, vastly prefer to have two codepaths, and choose which one to use depending on the detected version of itstool:
- one where this is done properly
- one where strange file copying happens invisibly via private scripts that hide itstool from ninja and circumvent find_program_impl and repeatedly create tempdirs to repeatedly do file IO

2021-12-30 15:15 UTC, eli-schwartz commented
Hmmm... When I was fixing shared-mime-info use of itstool that ran a custom shellscriot which invoked ninja to build mo files, my first implementation actually ran cp to copy those files as ninja build rules, and then just ran itstool directly from ninja. This is more portably done as a meson internal copy.py script... Honestly I like that thought a lot better than layering it in a script with a tempdir.

However I never committed that code because I realized it could just use the better project via i18.merge_file; maybe gettext itself could be fixed to not have the bugs you say are there?

It is a bit inconvenient that itstool requires running msgfmt to generate .mo files which are never installed, when gettext can directly merge .po files into your xml.

2022-01-19 23:55 UTC, ximion commented
@eli-schwartz 
> It will take even longer if no one ever pushes to have this changed, so it never gets implemented. If we are going to handle this I'd vastly, vastly prefer to have two codepaths, and choose which one to use depending on the detected version of itstool

Sure, if/when `itstool` has gained support for this, we can do it! Annoyingly, a mo-file does not contain the locale string that it belongs to, so there is nothing clever we can do here, so I am not even sure how a proper solution that does not depend on file names would look like (it would always be some kind of heuristic for semi-clever locale name autodetection).

> It is a bit inconvenient that itstool requires running msgfmt to generate .mo files which are never installed, when gettext can directly merge .po files into your xml.

True, both tools are surprisingly inconvenient in respective corner cases... But at least `itstool` with its more limited scope does the job properly...

@jpakkane I addressed your style comments, and the resulting data is also now verified by a small Python script instead of using `grep` & Co.

2022-01-21 10:31 UTC, jpakkane commented on test cases/frameworks/6 gettext/data3/meson.build
> +mi_translated = i18n.itstool_join(
These should be indented.

2022-01-21 21:26 UTC, ximion commented on test cases/frameworks/6 gettext/data3/meson.build
> +mi_translated = i18n.itstool_join(
Done :-)

2022-01-21 22:05 UTC, eli-schwartz commented
> Sure, if/when `itstool` has gained support for this, we can do it!

Are you saying you've submitted a bug report to itstool for this? Great. Please link it here though.

2022-01-21 22:21 UTC, ximion commented
> > Sure, if/when `itstool` has gained support for this, we can do it!
> 
> Are you saying you've submitted a bug report to itstool for this? Great. Please link it here though.

There is https://github.com/itstool/itstool/issues/32 and https://github.com/itstool/itstool/issues/44 on this issue (with the latter being the specific issue that we work around here).

2022-01-21 23:01 UTC, merged

2022-01-23 03:05 UTC, eli-schwartz commented on docs/markdown/i18n-module.md
> +*Added 0.61.0*
This is out of date.

2022-01-23 03:05 UTC, eli-schwartz commented on mesonbuild/modules/i18n.py
> +    @FeatureNew('i18n.itstool_join', '0.61.0')
This is out of date.

2022-01-23 03:10 UTC, eli-schwartz commented on mesonbuild/modules/i18n.py
> +            self.noitstool_error()
This seems like a weird thing to delegate to a dispatch function as it is only used once, and we should really just use the find_program implementation, which respects tools defined in cross files, then pass it as an argument to the helper script.

2022-01-23 03:13 UTC, eli-schwartz commented on docs/markdown/i18n-module.md
> +*Added 0.61.0*
#9867