wraptool: status: Include filename in error message if wrap is not on wrapdb.
mesonbuild/meson pull request #9789
Opened 2022-01-07 21:32 UTC by sielicki

Would close #9787

Signed-off-by: Nicky Sielicki <sielicki@yandex.com>

2022-01-24 19:23 UTC, eli-schwartz requested changes

2022-01-24 19:23 UTC, eli-schwartz commented on mesonbuild/wrap/wraptool.py
> +            print('Wrap file "{}" not from wrapdb.'.format(name), file=sys.stderr)
```suggestion
            print(f'Wrap file {name!r} not from wrapdb.', file=sys.stderr)
```

f-strings are faster and often more concise than format functions.

2023-02-18 19:35 UTC, sielicki commented
fixed in fc5dfb852b

Closing.

2023-02-18 19:35 UTC, closed without merging

2023-02-19 01:49 UTC, eli-schwartz commented
Oh huh, so it was. :o