gnome.genmarshal: restore the ability to pass sources as Files objects
mesonbuild/meson pull request #9828
Opened 2022-01-14 20:22 UTC by eli-schwartz

It used to support:
- a single string
- an array of anything

And as long as CustomTarget supported it too, everything worked fine. So, a `files('foo')` worked but a `files('foo')[0]` did not, which is silly... and it's not exactly terrible to use files() here, the input is literally a list of source files.

Fixes building gnome-terminal
Fixes #9827

2022-01-14 20:29 UTC, dcbaker requested changes
It looks like we actually do document the type in the gnome module documentation, so we should fix that too.

2022-01-14 20:56 UTC, dcbaker commented on docs/markdown/Gnome-module.md
>  * `sources`: the list of sources to use as inputs
We should at least kee the `*required*` here I think.

2022-01-14 21:04 UTC, nirbheek commented
Failing test on Arch Linux is `17 mpi` segfaulting, which happens from time to time.

2022-01-15 03:16 UTC, dcbaker approved these changes

2022-01-15 12:10 UTC, nirbheek commented
New test is failing because glib-genmarshal actually can't handle multiple source arguments correctly. Fixing...

2022-01-15 18:20 UTC, merged